apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app openebs
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    alloy:
      enabled: false
    engines:
      local:
        lvm:
          enabled: true
        rawfile:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    localpv-provisioner:
      hostpathClass:
        enabled: false
      localpv:
        enabled: false
      rbac:
        create: false
      serviceAccount:
        create: false
    loki:
      enabled: false
    lvm-localpv:
      analytics:
        enabled: false
      crds:
        csi:
          volumeSnapshots:
            enabled: false
        lvmLocalPv:
          enabled: true
      lvmNode:
        kubeletDir: /var/lib/kubelet/
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
    preUpgradeHook:
      enabled: false
