apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app openebs
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    analytics:
      enabled: false
    localpv:
      basePath: /var/mnt/local-hostpath
