NFS_CORE_PARAM {
    NFS_Protocols = 4;
    NFS_Port = 2049;
    Enable_NLM = false;
    Enable_RQUOTA = false;
    Enable_UDP = false;
    Allow_Set_Io_Flusher_Fail = true;
}

NFSV4 {
    Grace_Period = 90;
}

EXPORT_DEFAULTS {
    Access_Type = NONE;
    Squash = Root_Squash;
    SecType = sys;
    Protocols = 4;
    Transports = TCP;
}

EXPORT {
    Export_Id = 1001;
    Path = /export/media-rw;
    Pseudo = /media-rw;

    Access_Type = RW;
    Squash = Root_Squash;
    SecType = sys;
    Protocols = 4;
    Transports = TCP;

    CLIENT {
        Clients = 10.0.10.101, 10.0.10.102, 10.0.10.103;
        Access_Type = RW;
        Squash = Root_Squash;
    }

    FSAL {
        Name = VFS;
    }
}

EXPORT {
    Export_Id = 1002;
    Path = /export/media-nc;
    Pseudo = /media-nc;

    Access_Type = RW;
    Squash = Root_Squash;
    SecType = sys;
    Protocols = 4;
    Transports = TCP;

    CLIENT {
        Clients = 10.0.40.215;
        Access_Type = RW;
        Squash = Root_Squash;
    }

    FSAL {
        Name = VFS;
    }
}
