---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: kube-prometheus-stack
  values:
    crds:
      enabled: true
    cleanPrometheusOperatorObjectNames: true
    alertmanager:
      enabled: false
    kubeApiServer:
      serviceMonitor:
        metricRelabelings:
          - action: drop
            sourceLabels: ["__name__"]
            regex: (apiserver|etcd|rest_client)_request(|_sli|_slo)_duration_seconds_bucket
          - action: drop
            sourceLabels: ["__name__"]
            regex: (apiserver_response_sizes_bucket|apiserver_watch_events_sizes_bucket)
    kubeControllerManager:
      enabled: false
    kubeEtcd:
      enabled: false
    kubelet:
      serviceMonitor:
        metricRelabelings:
          - action: labeldrop
            regex: (uid)
          - action: labeldrop
            regex: (id|name)
          - action: drop
            sourceLabels: ["__name__"]
            regex: (rest_client_request_duration_seconds_bucket|rest_client_request_duration_seconds_sum|rest_client_request_duration_seconds_count)
    kubeProxy:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
    grafana:
      enabled: true
      envFromSecrets:
        - name: grafana-oauth-secret
      grafana.ini:
        server:
          root_url: https://grafana.${DOMAIN_0}
        auth:
          disable_login_form: true
        auth.basic:
          enabled: false
        auth.generic_oauth:
          enabled: true
          name: Pocket ID
          allow_sign_up: true
          allow_assign_grafana_admin: true
          allowed_groups: admin
          api_url: https://id.${DOMAIN_0}/api/oidc/userinfo
          auth_url: https://id.${DOMAIN_0}/authorize
          auto_login: true
          client_id: eddd917b-ee07-4f5b-b086-6d3cbcd8c4ec
          groups_attribute_path: groups
          jwk_set_url: https://id.${DOMAIN_0}/.well-known/jwks.json
          login_attribute_path: preferred_username
          role_attribute_path: "contains(groups[*], 'admin') && 'GrafanaAdmin' || 'Viewer'"
          role_attribute_strict: true
          scopes: openid profile email groups
          token_url: https://id.${DOMAIN_0}/api/oidc/token
          use_pkce: true
      resources:
        requests: { cpu: 50m, memory: 128Mi }
        limits: { memory: 512Mi }
      route:
        main:
          enabled: true
          hostnames: ["grafana.${DOMAIN_0}"]
          parentRefs:
            - name: envoy-internal
              namespace: envoy-gateway
              sectionName: https
      sidecar:
        datasources:
          alertmanager:
            enabled: false
    prometheusOperator:
      resources:
        requests: { cpu: 10m, memory: 100Mi }
    prometheusConfigReloader:
      resources:
        requests: { cpu: 10m, memory: 100Mi }
    prometheus:
      prometheusSpec:
        serviceDiscoveryRole: EndpointSlice
        version: v2.55.1
        image:
          registry: docker.io
          repository: prompp/prompp
          tag: 0.7.10
          sha: 405dbe39fe3ca1daf9a942a047418c153ace49ccbb91c5ad029552be27b96446
        securityContext:
          runAsNonRoot: true
          runAsUser: 64535
          runAsGroup: 64535
          fsGroup: 64535
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        scrapeConfigSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        enableFeatures: [memory-snapshot-on-shutdown]
        retention: 14d
        retentionSize: 50GB
        resources:
          requests: { cpu: 100m }
          limits: { memory: 2000Mi }
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: ceph-block
              resources:
                requests: { storage: 50Gi }
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
    prometheus-node-exporter:
      fullnameOverride: node-exporter
      prometheus:
        monitor:
          enabled: true
          relabelings:
            - action: replace
              regex: (.*)
              replacement: $1
              sourceLabels: ["__meta_kubernetes_pod_node_name"]
              targetLabel: kubernetes_node
