apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: _
      spec:
        values:
          route:
            app:
              annotations:
                gethomepage.dev/enabled: "true"
                gethomepage.dev/group: '{{ default (title "${domain}") "${HOMEPAGE_GROUP:=}" }}'
                gethomepage.dev/icon: '{{ default (printf "sh-%s.svg" (regexReplaceAll "-[0-9]+$" .Release.Name "")) "${HOMEPAGE_ICON:=}" }}'
                gethomepage.dev/name: '{{ default (.Release.Name | title) "${HOMEPAGE_NAME:=}" }}'
                gethomepage.dev/pod-selector: '{{ default (printf "app.kubernetes.io/instance=%s,app.kubernetes.io/name=%s" .Release.Name .Release.Name) "${HOMEPAGE_POD_SELECTOR:=}" }}'
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: .*
