---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app node-network-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    config:
      webhook:
        enableTLS: true
        issuerRef:
          kind: ClusterIssuer
          name: selfsigned
    resources:
      serviceMonitor:
        cluster:
          enabled: false
        node:
          enabled: false
