apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../patches
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: _
      spec:
        values:
          persistence:
            tmp:
              type: emptyDir
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
