---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-gluetun-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ${APP}-gluetun-secret
    template:
      engineVersion: v2
      data:
        GLUETUN_API_KEY: "{{ .GLUETUN_API_KEY }}"
        config.toml: |
          [[roles]]
          name = "port-forward"
          routes = ["GET /v1/portforward"]
          auth = "apikey"
          apikey = "{{ .GLUETUN_API_KEY }}"
        vpn_service_provider: "{{ .VPN_SERVICE_PROVIDER }}"
        wireguard_private_key: "{{ .WIREGUARD_PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: ${APP}
