# yaml-language-server: $schema=https://www.schemastore.org/any.json
---
apiVersion: gluetun.k8s-gitops.io/v1alpha1
kind: GluetunClient
metadata:
  name: ${APP}
spec:
  gateway: ${GLUETUN_GATEWAY_NAME}
  service: ${GLUETUN_SERVICE:=${APP}}
