---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - externalsecret.yaml
patches:
  - path: patches/gluetun.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
  - path: patches/socks5.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
  - path: patches/services.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
