---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      pocket-id:
        initContainers:
          db-wait:
            image:
              repository: postgres
              tag: "18.4-alpine3.23@sha256:7764e781145fa1b70b8ebd6f440d3372fdd985a26ce0039dcba8442d22c8c36e"
            command: ["/bin/sh", "-ec"]
            args: ["until pg_isready -q -h ${APP}-cnpg-rw -p 5432 -U postgres -d postgres; do sleep 2; done"]
            securityContext: &securityContext
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
        containers:
          app:
            image:
              repository: ghcr.io/pocket-id/pocket-id
              tag: v2.8.0@sha256:a073640418b2cfc8587c488a7270580b3ab95cae2c543f5d64bbbe1fd7ccbae8
            env:
              PUID: "568"
              PGID: "568"
              APP_NAME: Freeman ID
              HOME_PAGE_URL: /settings/apps
              APP_URL: https://id.${DOMAIN_0}
              TRUST_PROXY: true
              TRUSTED_PLATFORM: CF-Connecting-IP
              FILE_BACKEND: database
              ANALYTICS_DISABLED: true
              VERSION_CHECK_DISABLED: true
              UI_CONFIG_DISABLED: true
              EMAILS_VERIFIED: true
              EMAIL_ONE_TIME_ACCESS_AS_ADMIN_ENABLED: true
              EMAIL_VERIFICATION_ENABLED: true
              ACCENT_COLOR: '#FAAAFF'
              SMTP_HOST: ${SMTP_HOST_0}
              SMTP_PORT: 587
              SMTP_TLS: starttls
              SMTP_FROM: id@${DOMAIN_0}
              SMTP_USER: ${SMTP_USERNAME_0}
              SMTP_PASSWORD_FILE: /secrets/SMTP_PASSWORD_0
              MAXMIND_LICENSE_KEY_FILE: /secrets/MAXMIND_LICENSE_KEY
              ENCRYPTION_KEY_FILE: /secrets/ENCRYPTION_KEY
              DB_CONNECTION_STRING:
                valueFrom:
                  secretKeyRef:
                    name: pocket-id-cnpg-app
                    key: fqdn-uri
            probes:
              liveness: &probes
                custom: true
                spec:
                  exec:
                    command: ["/app/pocket-id", "healthcheck"]
              readiness: *probes
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 512Mi
            securityContext: *securityContext
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
    persistence:
      secret:
        type: secret
        name: pocket-id-app-secret
        globalMounts:
          - path: /secrets
      data:
        type: emptyDir
        globalMounts:
          - path: /app/data
    route:
      app:
        hostnames: ['id.${DOMAIN_0}']
        parentRefs:
          - name: envoy-external
            namespace: envoy-gateway
            sectionName: https
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /setup
              - path:
                  type: PathPrefix
                  value: /signup
            filters:
              - type: RequestRedirect
                requestRedirect:
                  path:
                    type: ReplaceFullPath
                    replaceFullPath: /login
                  statusCode: 302
          - backendRefs:
              - identifier: app
                port: 1411
    service:
      app:
        ports:
          http:
            port: 1411
