---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret kometa-app-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        .env: |
          KOMETA_PLEXTOKEN={{ .PLEX_TOKEN }}
          KOMETA_RADARRAPIKEY={{ .RADARR_API_KEY }}
          KOMETA_SONARRAPIKEY={{ .SONARR_API_KEY }}
          KOMETA_TMDBAPIKEY={{ .TMDB_API_KEY }}
  dataFrom:
    - extract:
        key: plex
    - extract:
        key: radarr
    - extract:
        key: sonarr
