---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret flux-operator-app-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  dataFrom:
    - extract:
        key: flux-operator
  target:
    name: *secret
    template:
      engineVersion: v2
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
      data:
        values.yaml: |
          web:
            config:
              authentication:
                oauth2:
                  clientSecret: "{{ .OIDC_CLIENT_SECRET }}"
