apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: flux-operator
  values:
    serviceMonitor:
      create: true
    web:
      enabled: true
      networkPolicy:
        create: false
      config:
        baseURL: https://flux.${DOMAIN_0}
        authentication:
          type: OAuth2
          oauth2:
            provider: OIDC
            clientID: 22b48539-9dae-487b-907b-f63d48385aa9
            issuerURL: https://id.${DOMAIN_0}
            impersonation:
              username: "claims.email"
              groups: "claims.groups"
            scopes: [openid, profile, email, groups]
            validations:
              - expression: "has(claims.groups) && size(claims.groups) > 0"
                message: user must belong to at least one Pocket ID group
      httpRoute:
        enabled: true
        parentRefs:
          - name: envoy-internal
            namespace: envoy-gateway
            sectionName: https
        hostnames: ["flux.${DOMAIN_0}"]
  valuesFrom:
    - kind: Secret
      name: flux-operator-app-secret
      valuesKey: values.yaml
