apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: flux-operator
  values:
    serviceMonitor:
      create: true
    web:
      enabled: true
      networkPolicy:
        create: false
      config:
        baseURL: https://flux.${DOMAIN_0}
        authentication:
          type: OAuth2
          oauth2:
            provider: OIDC
            clientID: flux-operator
            issuerURL: https://auth.${DOMAIN_0}
            scopes: [openid, profile, email, groups]
      httpRoute:
        enabled: true
        parentRefs:
          - name: envoy-internal
            namespace: envoy-gateway
            sectionName: https
        hostnames: ["flux.${DOMAIN_0}"]
  valuesFrom:
    - kind: Secret
      name: flux-operator-app-secret
      valuesKey: OIDC_CLIENT_SECRET
      targetPath: web.config.authentication.oauth2.clientSecret
