---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret mealie-app-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
  dataFrom:
    - extract:
        key: mealie
  data:
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: smtp
        property: SMTP_PASSWORD_0
