---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      mealie:
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.22.0@sha256:36c28f0642fb6c75fae8997a2d55994631b9b4bcffba3016c208fc132a4c1e69
            env:
              PUID: 568
              PGID: 568
              BASE_URL: https://mealie.${DOMAIN_0}
              DB_ENGINE: postgres
              POSTGRES_SERVER: mealie-cnpg-rw
              POSTGRES_PASSWORD_FILE: /secrets/cnpg/password
              ALLOW_PASSWORD_LOGIN: false
              OIDC_AUTH_ENABLED: true
              OIDC_AUTO_REDIRECT: true
              OIDC_CLIENT_ID: ac74a56e-8c76-411e-90fa-47fd13113d45
              OIDC_CLIENT_SECRET_FILE: /secrets/app/OIDC_CLIENT_SECRET
              OIDC_CONFIGURATION_URL: https://id.${DOMAIN_0}/.well-known/openid-configuration
              OIDC_PROVIDER_NAME: Freeman ID
              OIDC_REMEMBER_ME: true
              SMTP_AUTH_STRATEGY: TLS
              SMTP_FROM_EMAIL: id@${DOMAIN_0}
              SMTP_HOST: ${SMTP_HOST_0}
              SMTP_USER: ${SMTP_USERNAME_0}
              SMTP_PASSWORD_FILE: /secrets/app/SMTP_PASSWORD
              SMTP_PORT: 587
              THEME_LIGHT_PRIMARY: '#75A86C'
              THEME_LIGHT_ACCENT: '#A8D0A6'
              THEME_LIGHT_SECONDARY: '#638E5E'
              THEME_LIGHT_SUCCESS: '#4CAF50'
              THEME_LIGHT_INFO: '#4A9ED8'
              THEME_LIGHT_WARNING: '#EAC46B'
              THEME_LIGHT_ERROR: '#E57373'
              THEME_DARK_PRIMARY: '#739B7A'
              THEME_DARK_ACCENT: '#9FBE9D'
              THEME_DARK_SECONDARY: '#56775E'
              THEME_DARK_SUCCESS: '#81C784'
              THEME_DARK_INFO: '#78B2C0'
              THEME_DARK_WARNING: '#EBC86E'
              THEME_DARK_ERROR: '#E57373'
            probes:
              liveness: &probes
                enabled: true
                type: HTTP
                path: /api/app/about
              readiness: *probes
            resources:
              requests:
                cpu: 25m
                memory: 512Mi
              limits:
                memory: 1Gi
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
    persistence:
      data:
        existingClaim: mealie-data
        globalMounts:
          - path: /app/data
      secrets:
        type: secret
        name: mealie-app-secret
        globalMounts:
          - path: /secrets/app
      cnpg-secret:
        type: secret
        name: mealie-cnpg-app
        globalMounts:
          - path: /secrets/cnpg
    route:
      app:
        hostnames: ['mealie.${DOMAIN_0}']
        parentRefs:
          - name: envoy-internal
            namespace: envoy-gateway
            sectionName: https
    service:
      app:
        ports:
          http:
            port: 9000
