---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret grafana-oauth-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
  dataFrom:
    - extract:
        key: grafana
---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-oidc-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-oidc-secret
  dataFrom:
    - extract:
        key: alertmanager
