---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: alertmanager-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: kps-alertmanager
  oidc:
    provider:
      issuer: https://id.${DOMAIN_0}
    clientIDRef:
      name: alertmanager-oidc-secret
    clientSecret:
      name: alertmanager-oidc-secret
    cookieNames:
      idToken: alertmanager-oidc-token
    scopes: [groups]
    redirectURL: https://alertmanager.${DOMAIN_0}/oauth2/callback
  jwt:
    providers:
      - name: pocketid
        issuer: https://id.${DOMAIN_0}
        remoteJWKS:
          uri: https://id.${DOMAIN_0}/.well-known/jwks.json
        extractFrom:
          cookies: [alertmanager-oidc-token]
  authorization:
    defaultAction: Deny
    rules:
      - name: allow-oidc-groups
        action: Allow
        principal:
          jwt:
            provider: pocketid
            claims:
              - name: groups
                valueType: StringArray
                values: [admin]
