---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
labels:
  - fields:
      - path: metadata/labels
        create: true
      - group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        path: spec/postBuild/substitute
        create: true
    pairs:
      domain: media
resources:
  - autobrr/ks.yaml
  - bazarr/ks.yaml
  - grimmory/ks.yaml
  - maintainerr/ks.yaml
  - nzb/sabnzbd-1/ks.yaml
  - nzb/sabnzbd-2/ks.yaml
  - torrent/qbittorrent-2/ks.yaml
  - plex/ks.yaml
  - plex/imagemaid/ks.yaml
  - plex/kometa/ks.yaml
  - plex/plex/ks.yaml
  - plex/plex-auto-languages/ks.yaml
  - prowlarr/ks.yaml
  - radarr/ks.yaml
  - recyclarr/ks.yaml
  - romm/ks.yaml
  - seerr/ks.yaml
  - sonarr/ks.yaml
  - torrent/ks.yaml
  - torrent/qbittorrent-1/ks.yaml
  - torrent/qbittorrent-2/ks.yaml
  - torrent/qbittorrent-3/ks.yaml
  - torrent/qbittorrent-4/ks.yaml
  - torrent/qui/ks.yaml
  - tracearr/ks.yaml
