---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/common/domain
configMapGenerator:
  - name: domain
    literals: [DOMAIN=media]
generatorOptions:
  annotations:
    config.kubernetes.io/local-config: "true"
labels:
  - pairs:
      domain: media
namespace: flux-system
resources:
  - autobrr/ks.yaml
  - grimmory/ks.yaml
  - torrent/ks.yaml
  - torrent/qb1/ks.yaml
  # - torrent/qb2/ks.yaml
  # - torrent/qb3/ks.yaml
  # - torrent/qb4/ks.yaml
  # - torrent/qbitmanage/ks.yaml
  - romm/ks.yaml
