apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: scripts
    files:
      - storage-mapping.sh=./scripts/storage-mapping.sh
generatorOptions:
  disableNameSuffixHash: true
