---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: toolhive-crds
spec:
  interval: 1h
  path: kubernetes/apps/core/toolhive/crds
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: toolhive
  timeout: 10m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: toolhive-operator
spec:
  dependsOn:
    - name: toolhive-crds
  interval: 1h
  path: kubernetes/apps/core/toolhive/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: toolhive
  timeout: 10m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: toolhive-gateway
spec:
  components:
    - ../../../../components/dragonfly
  dependsOn:
    - name: dragonfly-operator
    - name: envoy-gateway-config
    - name: external-secrets-store
    - name: toolhive-operator
  interval: 1h
  path: kubernetes/apps/core/toolhive/gateway
  postBuild:
    substitute:
      APP: toolhive
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: toolhive
  timeout: 10m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: toolhive-tunnel
spec:
  components:
    - ../../../../components/common/app/shared
  dependsOn:
    - name: external-secrets-store
    - name: toolhive-gateway
  interval: 1h
  path: kubernetes/apps/core/toolhive/tunnel
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: toolhive
  timeout: 10m
  wait: true
