---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sabnzbd-2
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../components/common/app/shared
    - ../../../../../components/envoy-oidc
    - ../../../../../components/volsync
    - ../../../../../components/vpn
  dependsOn:
    - name: envoy-gateway-config
    - name: external-secrets-store
    - name: gluetun-delta
    - name: nzb
    - name: openebs
    - name: rook-ceph-cluster
    - name: volsync
  interval: 1h
  path: kubernetes/apps/media/nzb/sabnzbd-2/app
  postBuild:
    substitute:
      APP: *app
      VPN_GATEWAY_NAME: gluetun-delta
      VPN_GATEWAY_ID: "4"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: nzb
  timeout: 5m
  wait: true
