# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

set: [pipefail]
shopt: [globstar]

vars:
  NODES: { sh: "talosctl config info --output json | jq --join-output '[.nodes[]] | join(\",\")'" }
  RANDOM_CONTROLLER: { sh: "talosctl config info --output json | jq --raw-output '.endpoints[]' | shuf -n 1" }

env:
  OP_VAULT: Kubernetes
  AWS_ACCESS_KEY_ID: { sh: 'op read "op://{{.OP_VAULT}}/backblaze/AWS_ACCESS_KEY_ID"' }
  AWS_SECRET_ACCESS_KEY: { sh: 'op read "op://{{.OP_VAULT}}/backblaze/AWS_SECRET_ACCESS_KEY"' }
  RESTIC_PASSWORD: { sh: 'op read "op://{{.OP_VAULT}}/backblaze/RESTIC_PASSWORD"' }
  S3_BUCKET: { sh: 'op read "op://{{.OP_VAULT}}/backblaze/S3_BUCKET"' }
  S3_ENDPOINT: { sh: 'op read "op://{{.OP_VAULT}}/backblaze/S3_ENDPOINT"' }

includes:
  bootstrap: .taskfiles/bootstrap/Taskfile.yaml
  cnpg: .taskfiles/cnpg/Taskfile.yaml
  flux: .taskfiles/flux/Taskfile.yaml
  kubernetes: .taskfiles/kubernetes/Taskfile.yaml
  talos: .taskfiles/talos/Taskfile.yaml
  volsync: .taskfiles/volsync/Taskfile.yaml
