---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rook-ceph
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/common
  interval: 1h
  patches:
    - target:
        kind: Namespace
      patch: |-
        - op: add
          path: /metadata/annotations
          value:
            kustomize.toolkit.fluxcd.io/prune: disabled
  path: kubernetes/apps/system/rook-ceph/app
  postBuild:
    substitute:
      POD_SECURITY_ENFORCE: privileged
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: *app
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app rook-ceph-cluster
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: rook-ceph
  dependsOn:
    - name: envoy-gateway-config
    - name: external-secrets-store
    - name: rook-ceph
    - name: snapshot-controller
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: rook-ceph
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      name: rook-ceph
      namespace: rook-ceph
  healthCheckExprs:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      failed: status.ceph.health == 'HEALTH_ERR'
      current: status.ceph.health in ['HEALTH_OK', 'HEALTH_WARN']
  interval: 1h
  path: kubernetes/apps/system/rook-ceph/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: rook-ceph
  timeout: 15m
  wait: true
