# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/postgresql.cnpg.io/clusterimagecatalog_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql-ossapps
  labels:
    app.kubernetes.io/managed-by: gitops
    images.freedscript.io/profile: ossapps
spec:
  images:
    - major: 17
      image: docker.io/ossapps/postgres:18.3-trixie@sha256:6f057a7b35ece59fa6b2beba1bf694539fb33ba4b9a42de0de13322ea5db5c48
