---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app soju
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/common/app
    - ../../../../components/cnpg
    - ../../../../components/gluetun
  dependsOn:
    - name: cert-manager-issuers
    - name: cloudnative-pg
    - name: external-dns
    - name: external-secrets-store
    - name: gluetun-echo
    - name: openebs
  interval: 1h
  path: kubernetes/apps/services/soju/app
  patches:
    - patch: |-
        - op: replace
          path: /spec/bootstrap
          value:
            initdb:
              database: soju
              owner: soju
      target:
        group: postgresql.cnpg.io
        kind: Cluster
  postBuild:
    substitute:
      APP: *app
      VPN_GATEWAY_ID: "5"
      VPN_GATEWAY_NAME: gluetun-echo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: *app
  timeout: 5m
  wait: true
