---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret flux-common
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    template:
      metadata:
        labels:
          reconcile.fluxcd.io/watch: Enabled
  dataFrom:
    - extract:
        key: common
  data:
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: backblaze
        property: S3_ENDPOINT
    - secretKey: S3_BUCKET
      remoteRef:
        key: backblaze
        property: S3_BUCKET
