---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: autobrr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      autobrr:
        containers:
          app:
            image:
              repository: ghcr.io/autobrr/autobrr
              tag: v1.83.0@sha256:7e8ce4ec9397685762dc7d8426c976cb15bd36522fac91dfd3648a4c57c6d358
            env:
              AUTOBRR__OIDC_ENABLED: true
              AUTOBRR__OIDC_ISSUER: https://id.${DOMAIN_0}
              AUTOBRR__OIDC_REDIRECT_URL: https://autobrr.${DOMAIN_1}/api/auth/oidc/callback
              AUTOBRR__OIDC_CLIENT_ID: 5b23a619-d404-437f-b8f5-40bf4d3a684d
              AUTOBRR__OIDC_CLIENT_SECRET_FILE: /secrets/OIDC_CLIENT_SECRET
              AUTOBRR__OIDC_DISABLE_BUILT_IN_LOGIN: true
            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /api/healthz/liveness
              readiness:
                enabled: true
                type: HTTP
                path: /api/healthz/readiness
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
    persistence:
      config:
        existingClaim: 'autobrr-data'
      secrets:
        type: secret
        name: autobrr-app-secret
    route:
      app:
        hostnames: ['autobrr.${DOMAIN_1}']
        parentRefs:
          - name: envoy-internal
            namespace: envoy-gateway
            sectionName: https
    service:
      app:
        ports:
          http:
            port: 7474
