apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
replacements:
  - source:
      kind: ConfigMap
      name: domain
      fieldPath: data.DOMAIN
    targets:
      - select:
          group: kustomize.toolkit.fluxcd.io
          version: v1
          kind: Kustomization
        fieldPaths:
          - spec.postBuild.substitute.DOMAIN
        options:
          create: true
