---
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServerEntry
metadata:
  name: ${APP}
  namespace: toolhive
spec:
  allowPrivateEndpoint: true
  groupRef:
    name: ${TOOLHIVE_MCP_GROUP:=toolhive-mcp}
  remoteUrl: http://${APP}-mcp.${NAMESPACE:=${APP}}.svc.cluster.local:${TOOLHIVE_MCP_PORT}/mcp
  transport: streamable-http
