exclude:
  platforms:
    - arcade-atomiswave
    - arcade-mame
    - arcade-model2
    - arcade-model3
    - arcade-naomi
    - arcade-naomi2
    - microsoft-dos
system:
  platforms:
    amiga-cd32: amiga-cd32
    atari-2600: atari2600
    atari-7800: atari7800
    atari-jaguar: jaguar
    atari-lynx: lynx
    coleco-colecovision: colecovision
    gce-vectrex: vectrex
    magnavox-odyssey2: odyssey
    mattel-intellivision: intellivision
    microsoft-xbox: xbox
    microsoft-xbox.360: xbox360
    nec-pc.fx: pc-fx
    nec-supergrafx: supergrafx
    nec-turbografx.16: tg16
    nec-turbografx.cd: turbografx-cd
    nintendo-64: n64
    nintendo-famicom: famicom
    nintendo-famicom.disk.system: fds
    nintendo-gameboy: gb
    nintendo-gameboy.advance: gba
    nintendo-gameboy.color: gbc
    nintendo-gamecube: ngc
    nintendo-nes: nes
    nintendo-snes: snes
    nintendo-super.famicom: sfam
    nintendo-switch: switch
    nintendo-virtual.boy: virtualboy
    nintendo-wii: wii
    nintendo-wii.u: wiiu
    nintendo.3ds: 3ds
    nintendo.ds: nds
    panasonic-3do: 3do
    philips.cdi: philips-cd-i
    sega-32x: sega32
    sega-cd: segacd
    sega-dreamcast: dc
    sega-gamegear: gamegear
    sega-genesis: genesis
    sega-master.system: sms
    sega-saturn: saturn
    sega-sg1000: sg1000
    snk-neogeo.aes: neogeoaes
    snk-neogeo.cd: neo-geo-cd
    snk-neogeo.pocket.color: neo-geo-pocket-color
    sony-playstation.1: psx
    sony-playstation.2: ps2
    sony-playstation.3: ps3
    sony-playstation.portable: psp
    sony-playstation.vita: psvita
filesystem:
  roms_folder: "games"
scan:
  priority:
    metadata:
      - "launchbox"
    artwork:
      - "launchbox"
media:
  - box2d
  - box3d
  - physical
  - screenshot
  - title_screen
  - fanart
  - bezel
  - manual
  - video
  - box2d_back
  - marquee
