# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:

  reconcile:
    desc: Reconcile Flux Kustomization with source [APP=optional]
    cmds:
      - flux reconcile kustomization {{.NAME | shellQuote}} -n flux-system --with-source
      - task: watch
        vars:
          APP: '{{.APP}}'
    vars:
      NAME: '{{.APP | default "cluster-apps"}}'
    preconditions:
      - which flux

  watch:
    desc: Watch Flux status [APP=optional]
    silent: true
    cmd: bash .taskfiles/flux/scripts/watch.sh {{.APP | default "" | shellQuote}}
    preconditions:
      - test -f .taskfiles/flux/scripts/watch.sh
      - which awk bash flux kubectl sed sleep stty tput
