apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
labels:
  - fields:
      - path: metadata/labels
        create: true
      - group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        path: spec/postBuild/substitute
        create: true
    pairs:
      domain: services
resources:
  - flatnotes/ks.yaml
  - homepage/ks.yaml
  - immich/ks.yaml
  - mealie/ks.yaml
  - splitpro/ks.yaml
