apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/common/domain
configMapGenerator:
  - name: domain
    literals: [DOMAIN=services]
generatorOptions:
  annotations:
    config.kubernetes.io/local-config: "true"
labels:
  - pairs:
      domain: services
namespace: flux-system
resources:
  - flatnotes/ks.yaml
  - homepage/ks.yaml
  - immich/ks.yaml
  - splitpro/ks.yaml
