# yaml-language-server: $schema=https://www.schemastore.org/any.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-volsync-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ${APP}-volsync-secret
    template:
      engineVersion: v2
      mergePolicy: Merge
      data:
        RESTIC_REPOSITORY: s3:https://{{ .S3_ENDPOINT }}/{{ .S3_BUCKET }}/volsync/${APP}
  dataFrom:
    - extract:
        key: backblaze
