---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app envoy-gateway
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    config:
      envoyGateway:
        extensionApis:
          enableLua: true
        provider:
          type: Kubernetes
          kubernetes:
            deploy:
              type: GatewayNamespace
