apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../common/app/shared
configMapGenerator:
  - name: ${APP}-iptables
    files:
      - post-rules.txt=resources/post-rules.txt
    options:
      disableNameSuffixHash: true
resources:
  - externalsecret.yaml
  - gluetungateway.yaml
  - helmrelease.yaml
  - network.yaml
  - networkpolicy.yaml
  - rbac.yaml
