# yaml-language-server: $schema=https://www.schemastore.org/any.json
---
apiVersion: v1
kind: Pod
metadata:
  name: ${POD}
  labels:
    app.kubernetes.io/name: pvc-mount
spec:
  automountServiceAccountToken: false
  restartPolicy: Always
  securityContext:
    runAsNonRoot: true
    runAsUser: ${RUN_AS_USER}
    runAsGroup: ${RUN_AS_GROUP}
    fsGroup: ${RUN_AS_GROUP}
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: busybox
      image: docker.io/library/busybox:1.37.0
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - while true; do sleep 3600; done
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: [ALL]
      resources:
        requests:
          cpu: 5m
          memory: 16Mi
        limits:
          memory: 64Mi
      volumeMounts:
        - name: data
          mountPath: /volume
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: ${PVC}
