apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/common/domain
configMapGenerator:
  - name: domain
    literals: [DOMAIN=utils]
generatorOptions:
  annotations:
    config.kubernetes.io/local-config: "true"
labels:
  - pairs:
      domain: utils
namespace: flux-system
resources:
  - idrac-fan-controller/ks.yaml
