---
overlays:
  leaving_soon:
    plex_search:
      all:
        label: leaving-soon
    overlay:
      name: text(Retiré bientôt)
      back_align: center
      back_color: "#B20710"
      back_height: 80
      back_radius: 26
      back_width: 300
      font: /config/AvenirNextLTPro-Bold.ttf
      font_color: "#FFFFFF"
      font_size: 38
      horizontal_align: left
      horizontal_offset: 50
      vertical_align: bottom
      vertical_offset: 50
