---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret ${APP}-file-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        config.toml: |
          [[roles]]
          name = "port-forward"
          routes = ["GET /v1/portforward"]
          auth = "apikey"
          apikey = "{{ index . (printf "%s_GLUETUN_API_KEY" (replace "-" "_" (upper "${APP}"))) }}"
        GLUETUN_API_KEY: '{{ index . (printf "%s_GLUETUN_API_KEY" (replace "-" "_" (upper "${APP}"))) }}'
        WIREGUARD_PRIVATE_KEY: '{{ index . (printf "%s_WIREGUARD_PRIVATE_KEY" (replace "-" "_" (upper "${APP}"))) }}'
      mergePolicy: Replace
  dataFrom:
    - extract:
        key: gluetun
---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &env ${APP}-env-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *env
    template:
      engineVersion: v2
      data:
        VPN_SERVICE_PROVIDER: '{{ index . (printf "%s_VPN_SERVICE_PROVIDER" (replace "-" "_" (upper "${APP}"))) }}'
        WIREGUARD_ENDPOINT_IP: '{{ index . (printf "%s_WIREGUARD_ENDPOINT_IP" (replace "-" "_" (upper "${APP}"))) }}'
        WIREGUARD_ENDPOINT_PORT: '{{ index . (printf "%s_WIREGUARD_ENDPOINT_PORT" (replace "-" "_" (upper "${APP}"))) }}'
      mergePolicy: Replace
  dataFrom:
    - extract:
        key: gluetun
---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &agentSecret ${APP}-agent
spec:
  refreshPolicy: OnChange
  target:
    name: *agentSecret
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: gluetun-agent-token
