apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snapshot-controller
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    controller:
      replicaCount: 2
      podSecurityContext:
        seccompProfile:
          type: RuntimeDefault
      securityContext:
        allowPrivilegeEscalation: false
      serviceMonitor:
        create: true
    webhook:
      enabled: false
