---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMMCPServer
metadata:
  name: github
spec:
  authType: bearer_token
  authTokenRef:
    name: github-mcp-secret
    key: GITHUB_MCP_PAT
  url: https://api.githubcopilot.com/mcp
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-mcp-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: github-mcp-secret
  dataFrom:
    - extract:
        key: github-mcp
