---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app grimmory
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      grimmory:
        containers:
          grimmory:
            image:
              repository: ghcr.io/grimmory-tools/grimmory
              tag: v3.3.1@sha256:746bf67ac42b5c5f359946ccf4fcfee21129b876371965943c3400036fc2f170
            command: ["java"]
            args: ["-jar", "/app/app.jar"]
            env:
              DATABASE_URL: jdbc:mariadb://localhost:3306/grimmory
              DATABASE_USERNAME: *app
              APP_CORS_ALLOWED_ORIGINS: https://grimmory.${DOMAIN_1}
              JDK_JAVA_OPTIONS: --enable-native-access=ALL-UNNAMED
            envFrom:
              - secretRef:
                  name: grimmory-app-secret
            probes:
              liveness: &probes
                enabled: true
                type: HTTP
                path: /api/v1/healthcheck
              readiness: *probes
            resources:
              requests:
                cpu: 50m
                memory: 2Gi
              limits:
                memory: 6Gi
          mariadb:
            image:
              repository: docker.io/library/mariadb
              tag: 12.3.2-noble@sha256:c237fd50cc48d6f2b87c4ca66d52f3b5eef7271b3bea7aee586c0be19d5b460d
            args: [--innodb-use-native-aio=0]
            env:
              MARIADB_DATABASE: *app
              MARIADB_USER: *app
            envFrom:
              - secretRef:
                  name: grimmory-app-secret
        defaultContainerOptions:
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    persistence:
      data:
        existingClaim: grimmory-data
        advancedMounts:
          grimmory:
            grimmory:
              - path: /app/data
                subPath: app
            mariadb:
              - path: /var/lib/mysql
                subPath: mariadb/data
      media:
        type: custom
        volumeSpec:
          csi:
            driver: nfs.csi.k8s.io
            volumeAttributes:
              server: 10.0.10.10
              share: /mnt/eden/media
              mountOptions: soft
        advancedMounts:
          grimmory:
            grimmory:
              - path: /books
                subPath: library/books
              - path: /bookdrop
                subPath: temp/bookdrop
      mysqld:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Mi
        advancedMounts:
          grimmory:
            mariadb:
              - path: /run/mysqld
    route:
      app:
        forceRename: *app
        hostnames: ['grimmory.${DOMAIN_1}']
        parentRefs:
          - name: envoy-internal
            namespace: envoy-gateway
            sectionName: https
      kobo:
        hostnames: ['grimmory.${DOMAIN_1}']
        parentRefs:
          - name: envoy-internal
            namespace: envoy-gateway
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 6060
            matches:
              - path:
                  type: PathPrefix
                  value: /api/kobo
    service:
      app:
        ports:
          http:
            port: 6060
