apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - gluetunclient.yaml
  - networkpolicy.yaml
  - rbac.yaml
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: _
      spec:
        values:
          defaultPodOptions:
            affinity:
              podAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchLabels:
                        gluetun.k8s-gitops.io/gateway: ${VPN_GATEWAY_NAME}
                    namespaces: [gluetun]
                    topologyKey: kubernetes.io/hostname
            annotations:
              k8s.v1.cni.cncf.io/networks: "gluetun/${VPN_GATEWAY_NAME}-client@vpn"
            dnsConfig:
              nameservers: ["100.100.${VPN_GATEWAY_ID}.1"]
            dnsPolicy: None
            labels:
              gluetun.k8s-gitops.io/client-gateway: ${VPN_GATEWAY_NAME}
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
