apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - networkpolicy.yaml
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: _
      spec:
        values:
          defaultPodOptions:
            annotations:
              k8s.v1.cni.cncf.io/networks: "multus/gluetun-${VPN_GATEWAY}-client@vpn"
            dnsConfig:
              nameservers: ["${VPN_GATEWAY_IP}"]
            dnsPolicy: None
            labels:
              network.k8s-gitops.io/vpn-egress: ${VPN_GATEWAY}
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
