---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: ${APP}-egress
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: ${APP}
      network.k8s-gitops.io/vpn-egress: ${VPN_GATEWAY}
  egress:
    - toCIDRSet:
        - cidr: 100.100.${VPN_INSTANCE}.1/32
