---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret openchore-config-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          auth:
            public_url: https://openchore.${DOMAIN_0}
            oidc:
              - id: pocketid
                name: Freeman ID
                issuer: https://id.${DOMAIN_0}
                client_id: 835eddaf-7320-48f8-9017-8d21edafca0a
                client_secret: {{ .OIDC_CLIENT_SECRET | quote }}
                prompt: login
  dataFrom:
    - extract:
        key: openchore
