---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - recyclarr.yml=./resources/recyclarr.yml
      - radarr-encode.yml=./resources/includes/radarr-encode.yml
      - radarr-french.yml=./resources/includes/radarr-french.yml
      - radarr-original.yml=./resources/includes/radarr-original.yml
      - sonarr-anime.yml=./resources/includes/sonarr-anime.yml
      - sonarr-french.yml=./resources/includes/sonarr-french.yml
      - sonarr-original.yml=./resources/includes/sonarr-original.yml
    name: recyclarr-resources
generatorOptions:
  disableNameSuffixHash: true
resources:
  - externalsecret.yaml
  - helmrelease.yaml
