---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - files:
      - recyclarr.yml=./resources/recyclarr.yml
    name: recyclarr-config
  - files:
      - radarr.yml=./resources/includes/radarr.yml
      - sonarr.yml=./resources/includes/sonarr.yml
    name: recyclarr-resources
generatorOptions:
  disableNameSuffixHash: true
resources:
  - externalsecret.yaml
  - helmrelease.yaml
