---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm-app-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: litellm-app-secret
  dataFrom:
    - extract:
        key: litellm
