---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret glossarr-app-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
  data:
    - secretKey: TMDB_API_KEY
      remoteRef:
        key: common
        property: TMDB_API_KEY
    - secretKey: TVDB_API_KEY
      remoteRef:
        key: common
        property: TVDB_API_KEY
