apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/common/domain
configMapGenerator:
  - name: domain
    literals: [DOMAIN=core]
generatorOptions:
  annotations:
    config.kubernetes.io/local-config: "true"
labels:
  - pairs:
      domain: core
namespace: flux-system
resources:
  - cloudflared/ks.yaml
  - cloudnative-pg/ks.yaml
  - dragonfly/ks.yaml
  - envoy-gateway/ks.yaml
  - external-dns/ks.yaml
  - external-secrets/ks.yaml
  - gluetun/ks.yaml
  - gluetun/instances/alfa.yaml
  - gluetun/instances/bravo.yaml
  - onepassword-connect/ks.yaml
  - pocket-id/ks.yaml
  - volsync/ks.yaml
