---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - agent/configmap.yaml
  - agent/token-generator.yaml
  - configmap.yaml
  - helmrelease.yaml
  - rbac.yaml
configMapGenerator:
  - name: gluetun-router
    behavior: merge
    files:
      - handlers/qbittorrent.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
