---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gluetun-router
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gluetun-router
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gluetun-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gluetun-router
subjects:
  - kind: ServiceAccount
    name: gluetun-router
    namespace: gluetun
