---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app bambuddy
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: bambuddy
  components:
    - ../../../../components/common/app
    - ../../../../components/volsync
  dependsOn:
    - name: envoy-gateway-config
    - name: multus-networks
    - name: openebs
    - name: rook-ceph-cluster
    - name: volsync
  interval: 30m
  path: kubernetes/apps/domotics/bambuddy/app
  postBuild:
    substitute:
      APP: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: *app
  wait: true
