---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-secrets
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    serviceMonitor:
      enabled: true
