---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret external-dns-cloudflare-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    creationPolicy: Owner
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: external-dns
        property: CLOUDFLARE_API_TOKEN
