---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-cloudflare
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-dns
    namespace: flux-system
  values:
    fullnameOverride: *app
    logLevel: info
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare-secret
            key: CLOUDFLARE_API_TOKEN
    extraArgs:
      - --cloudflare-dns-records-per-page=1000
      - --cloudflare-proxied
      - --gateway-name=envoy-external
    policy: sync
    sources: [gateway-httproute]
    txtOwnerId: cloudflare
    txtPrefix: k8s.
    domainFilters:
      - ${DOMAIN_0}
      - ${DOMAIN_1}
      - ${DOMAIN_2}
    serviceMonitor:
      enabled: true
