# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.36.0-standalone-strict/mutatingadmissionpolicy-admissionregistration-v1.json
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicy
metadata:
  name: domain-labeler.k8s-gitops.io
spec:
  failurePolicy: Ignore
  matchConditions:
    - name: has-namespace-domain
      expression: namespaceObject != null && has(namespaceObject.metadata.labels) && "domain" in namespaceObject.metadata.labels && namespaceObject.metadata.labels["domain"] != ""
    - name: not-flux-kustomization
      expression: request.resource.group != "kustomize.toolkit.fluxcd.io" || request.resource.resource != "kustomizations"
  matchConstraints:
    resourceRules:
      - apiGroups: ["*"]
        apiVersions: ["*"]
        operations: ["CREATE"]
        resources: ["*"]
        scope: Namespaced
  mutations:
    - patchType: ApplyConfiguration
      applyConfiguration:
        expression: >
          Object{
            metadata: Object.metadata{
              labels: {"domain": namespaceObject.metadata.labels["domain"]}
            }
          }
  reinvocationPolicy: IfNeeded
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.36.0-standalone-strict/mutatingadmissionpolicybinding-admissionregistration-v1.json
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: domain-labeler.k8s-gitops.io
spec:
  policyName: domain-labeler.k8s-gitops.io
