# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.36.0-standalone-strict/mutatingadmissionpolicy-admissionregistration-v1.json
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicy
metadata:
  name: domain-labeler.k8s-gitops.io
spec:
  failurePolicy: Ignore
  matchConstraints:
    excludeResourceRules:
      - apiGroups: ["kustomize.toolkit.fluxcd.io"]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["kustomizations"]
        scope: Namespaced
    namespaceSelector:
      matchExpressions:
        - key: domain
          operator: Exists
    resourceRules:
      - apiGroups: [""]
        apiVersions: ["*"]
        operations: ["CREATE"]
        resources: ["*"]
        scope: Namespaced
      - apiGroups: ["*"]
        apiVersions: ["*"]
        operations: ["CREATE"]
        resources: ["*"]
        scope: Namespaced
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: >
          has(object.metadata.labels)
            ? [JSONPatch{op: "add", path: "/metadata/labels/domain", value: namespaceObject.metadata.labels["domain"]}]
            : [JSONPatch{op: "add", path: "/metadata/labels", value: {"domain": namespaceObject.metadata.labels["domain"]}}]
  reinvocationPolicy: IfNeeded
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.36.0-standalone-strict/mutatingadmissionpolicybinding-admissionregistration-v1.json
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: domain-labeler.k8s-gitops.io
spec:
  policyName: domain-labeler.k8s-gitops.io
