# yaml-language-server: $schema=https://www.schemastore.org/any.json
- System:
    - Observability:
        - Flux:
            id: flux
            icon: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/flux-operator.svg'
            href: 'https://flux.${DOMAIN_0}'
            namespace: flux-system
            podSelector: 'app.kubernetes.io/instance=flux-operator,app.kubernetes.io/name=flux-operator'
            siteMonitor: 'https://flux.${DOMAIN_0}'
            widgets:
                - type: customapi
                  url: >-
                    http://kps-prometheus.kube-prometheus-stack.svc.cluster.local:9090/api/v1/query?query=label_replace(flux_instance_info%7Bjob%3D%22flux-operator%22%7D%2C%22homepage%22%2C%22status%22%2C%22%22%2C%22%22)%20or%20label_replace((count(flux_resource_info%7Bready%3D%22True%22%2Csuspended%3D%22False%22%7D)%20or%20vector(0))%2C%22homepage%22%2C%22running%22%2C%22%22%2C%22%22)%20or%20label_replace((count(flux_resource_info%7Bkind%3D%22Kustomization%22%2Csuspended%3D%22True%22%7D)%20or%20vector(0))%2C%22homepage%22%2C%22suspended%22%2C%22%22%2C%22%22)
                  refreshInterval: 30000
                  mappings:
                      - field: 'data.result.0.metric.ready'
                        label: 'Status'
                        remap:
                            - value: 'True'
                              to: Up
                            - value: 'False'
                              to: Down
                      - field: 'data.result.1.value.1'
                        label: 'Running'
                        format: number
                      - field: 'data.result.2.value.1'
                        label: 'Suspended'
                        format: number
                - type: customapi
                  url: >-
                    http://kps-prometheus.kube-prometheus-stack.svc.cluster.local:9090/api/v1/query?query=label_replace(flux_resource_info%7Bkind%3D%22Kustomization%22%2Cready%3D%22False%22%2Csuspended%3D%22False%22%7D%2C%22homepage_reason%22%2C%22Failing%22%2C%22%22%2C%22%22)%20or%20label_replace(flux_resource_info%7Bkind%3D%22Kustomization%22%2Csuspended%3D%22True%22%7D%2C%22homepage_reason%22%2C%22Suspended%22%2C%22%22%2C%22%22)
                  refreshInterval: 30000
                  display: dynamic-list
                  mappings:
                      items: 'data.result'
                      name: 'metric.name'
                      label: 'metric.homepage_reason'
                      target: 'https://flux.${DOMAIN_0}/resource/{metric.kind}/{metric.namespace}/{metric.name}'
        - Grafana:
            icon: 'sh-grafana.svg'
            href: 'https://grafana.${DOMAIN_0}/bookmarks'
            namespace: kube-prometheus-stack
            podSelector: 'app.kubernetes.io/instance=kube-prometheus-stack,app.kubernetes.io/name=grafana'
            siteMonitor: 'https://grafana.${DOMAIN_0}'
            widgets:
                - type: prometheusmetric
                  url: 'http://kps-prometheus.kube-prometheus-stack.svc.cluster.local:9090'
                  refreshInterval: 30000
                  metrics:
                      - label: 'Total Alerts'
                        query: 'sum(alertmanager_alerts)'
                        format:
                            type: number
                      - label: 'Alerts Triggered'
                        query: 'sum(alertmanager_alerts{state="active"})'
                        format:
                            type: number
                - type: customapi
                  url: 'http://grafana.kube-prometheus-stack.svc.cluster.local/api/alertmanager/alertmanager/api/v2/alerts?active=true&silenced=false&inhibited=false&unprocessed=false'
                  headers:
                      Authorization: 'Bearer {{HOMEPAGE_FILE_GRAFANA_KEY}}'
                  refreshInterval: 30000
                  display: dynamic-list
                  mappings:
                      name: labels.alertname
                      label: labels.severity
                      target: 'https://grafana.${DOMAIN_0}/alerting/groups?alertmanager=Alertmanager&queryString=alertname%3D%22{labels.alertname}%22#homepage-alert-description={annotations.description}'
                      limit: 10
    - Operations:
        - Services: []
        - Domotics: []
        - Core: []
- Scale-1:
    - Storage:
        - TrueNAS:
            id: scale-1-truenas
            icon: 'sh-truenas-scale.svg'
            href: 'https://10.0.10.10'
            widget:
                type: truenas
                url: 'https://10.0.10.10'
                version: 2
                key: '{{HOMEPAGE_FILE_SCALE_01_KEY}}'
                enablePools: true
                nasType: scale
    - Glances:
        - CPU Usage:
            id: scale-1-glances
            widget:
                type: glances
                url: 'http://10.0.10.10:30015'
                version: 4
                metric: cpu
        - Memory Usage:
            widget:
                type: glances
                url: 'http://10.0.10.10:30015'
                version: 4
                metric: memory
        - Network Usage:
            widget:
                type: glances
                url: 'http://10.0.10.10:30015'
                version: 4
                metric: 'network:eth0'
        - Top Processes:
            widget:
                type: glances
                url: 'http://10.0.10.10:30015'
                version: 4
                metric: process
        - CPU Temp:
            widget:
                type: glances
                url: 'http://10.0.10.10:30015'
                version: 4
                metric: 'sensor:Package id 0'
        - Disk I/O:
            widget:
                type: glances
                url: 'http://10.0.10.10:30015'
                version: 4
                metric: 'disk:sdj'
- Scale-2:
    - Storage:
        - TrueNAS:
            id: scale-2-truenas
            icon: 'sh-truenas-scale.svg'
            href: 'https://10.0.10.11'
            widget:
                type: truenas
                url: 'https://10.0.10.11'
                version: 2
                key: '{{HOMEPAGE_FILE_SCALE_02_KEY}}'
                enablePools: true
                nasType: scale
    - Glances:
        - CPU Usage:
            id: scale-2-glances
            widget:
                type: glances
                url: 'http://10.0.10.11:30015'
                version: 4
                metric: cpu
        - Memory Usage:
            widget:
                type: glances
                url: 'http://10.0.10.11:30015'
                version: 4
                metric: memory
        - Network Usage:
            widget:
                type: glances
                url: 'http://10.0.10.11:30015'
                version: 4
                metric: 'network:eth0'
        - Top Processes:
            widget:
                type: glances
                url: 'http://10.0.10.11:30015'
                version: 4
                metric: process
        - CPU Temp:
            widget:
                type: glances
                url: 'http://10.0.10.11:30015'
                version: 4
                metric: 'sensor:Package id 0'
        - Disk I/O:
            widget:
                type: glances
                url: 'http://10.0.10.11:30015'
                version: 4
                metric: 'disk:sda'
- Media: []
