---
  # TAB 1 - ROW 1
- Servers:
  - Scale-1:
      icon: 'sh-truenas.svg'
      href: 'http://10.0.10.10'
      siteMonitor: 'http://10.0.10.10'
      widgets:
        - type: truenas
          url: 'http://10.0.10.10'
          version: 2
          key: '{{HOMEPAGE_FILE_SCALE_01_KEY}}'
          enablePools: 'true'
          nasType: 'scale'
  - Scale-2:
      icon: 'sh-truenas.svg'
      href: 'http://10.1.10.15'
      siteMonitor: 'http://10.1.10.15'
      widgets:
        - type: 'truenas'
          url: 'http://10.1.10.15'
          version: 2
          key: '{{HOMEPAGE_FILE_SCALE_02_KEY}}'
          enablePools: 'true'
          nasType: 'scale'
  - Plex:
      icon: 'sh-plex.svg'
      href: 'https://plex.${DOMAIN_1}'
      siteMonitor: 'http://plex.plex.svc.cluster.local:32400'
      namespace: 'plex'
      app: 'plex'
      podSelector: 'app.kubernetes.io/instance=plex,app.kubernetes.io/name=plex,pod.name=main'
  - Home Assistant:
      icon: 'sh-home-assistant.svg'
      href: 'https://home.${DOMAIN_0}'
      namespace: 'home-assistant'
      app: 'home-assistant'
      podSelector: 'app.kubernetes.io/instance=home-assistant,app.kubernetes.io/name=home-assistant,app.kubernetes.io/controller=app'
      siteMonitor: 'http://home-assistant.home-assistant.svc.cluster.local:8123'
      widgets:
        - type: 'homeassistant'
          fields: ["people_home", "lights_on", "switches_on"]
          key: '{{HOMEPAGE_FILE_HAOS_KEY}}'
          url: 'http://home-assistant.home-assistant.svc.cluster.local:8123'
  # TAB 1 - ROW 2
- Management:
  - Flux:
      icon: 'https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/flux-operator.svg'
      href: 'https://flux.${DOMAIN_0}'
      siteMonitor: 'http://flux-operator.flux-system.svc.cluster.local:9080'
      namespace: 'flux-system'
      app: 'flux-operator'
      podSelector: 'app.kubernetes.io/instance=flux-operator,app.kubernetes.io/name=flux-operator'
  - Grafana:
      icon: 'sh-grafana.svg'
      href: 'https://grafana.${DOMAIN_0}'
      siteMonitor: 'http://grafana.kube-prometheus-stack.svc.cluster.local'
      namespace: 'kube-prometheus-stack'
      app: 'grafana'
      podSelector: 'app.kubernetes.io/instance=kube-prometheus-stack,app.kubernetes.io/name=grafana'
  - Pocket ID:
      icon: 'sh-pocket-id-dark.svg'
      href: 'https://id.${DOMAIN_0}'
      siteMonitor: 'http://pocket-id.pocket-id.svc.cluster.local:1411'
      namespace: 'pocket-id'
      app: 'pocket-id'
      podSelector: 'app.kubernetes.io/instance=pocket-id,app.kubernetes.io/name=pocket-id,app.kubernetes.io/controller=pocket-id'
- Network:
  -  UDM-SE:
      icon: '/images/icons/udm-se.png'
      href: 'https://10.0.10.1'
      siteMonitor: 'https://10.0.20.1:443'
      widgets:
        - type: 'unifi'
          url: 'https://10.0.20.1:443'
          key: '{{HOMEPAGE_FILE_UDM_KEY}}'
          fields: ["uptime", "wan", "lan_users", "wlan_users"]
  -  UCG Ultra:
      icon: '/images/icons/ucg-ultra.png'
      href: 'https://10.1.10.1'
      siteMonitor: 'https://10.1.10.1:443'
      widgets:
        - type: 'unifi'
          url: 'https://10.1.10.1:443'
          key: '{{HOMEPAGE_FILE_UCG_KEY}}'
          fields: ["uptime", "wan", "lan_users"]
  -  Cloudflared:
      icon: 'sh-cloudflare.svg'
      href: 'https://one.dash.cloudflare.com/{{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNT_ID}}/networks/tunnels/cfd_tunnel/{{HOMEPAGE_VAR_CLOUDFLARED_TUNNEL_ID}}/edit?tab=publicHostname'
      siteMonitor: 'https://cloudflare.com'
      namespace: 'cloudflared'
      widgets:
        - type: 'cloudflared'
          accountid: '{{HOMEPAGE_VAR_CLOUDFLARED_ACCOUNT_ID}}'
          fields: ["status", "origin_ip"]
          key: '{{HOMEPAGE_FILE_CLOUDFLARED_KEY}}'
          tunnelid: '{{HOMEPAGE_VAR_CLOUDFLARED_TUNNEL_ID}}'
  # - Speedtest Tracker:
  #     icon: 'sh-speedtest-tracker.svg'
  #     href: 'https://speedtest.${DOMAIN_0}'
  #     siteMonitor: 'http://speedtest-tracker.speedtest-tracker.svc.cluster.local:9004'
  # - Changedetection.io:
  #     icon: 'sh-changedetection.svg'
  #     href: 'https://cdio.${DOMAIN_0}'
  #     siteMonitor: 'http://changedetection-io.changedetection.svc.cluster.local:5000'
  # TAB 2 - ROW 1
- Everyday Life:
  # - The Lounge:
  #     icon: 'sh-the-lounge.svg'
  #     href: 'https://irc.${DOMAIN_0}'
  #     siteMonitor: 'http://thelounge.thelounge.svc.cluster.local:10061'
  - Mealie:
      icon: 'sh-mealie.svg'
      href: 'https://mealie.${DOMAIN_0}'
      namespace: 'mealie'
      app: 'mealie'
      siteMonitor: 'http://mealie.mealie.svc.cluster.local:9000'
      widgets:
        - type: 'mealie'
          key: '{{HOMEPAGE_FILE_MEALIE_KEY}}'
          url: 'http://mealie.mealie.svc.cluster.local:9000'
          version: 2
  # - Homebox:
  #     icon: 'sh-homebox.svg'
  #     href: 'https://homebox.${DOMAIN_0}'
  #     namespace: 'homebox'
  - OpenChore:
      icon: 'mdi-broom'
      href: 'https://openchore.${DOMAIN_0}'
      namespace: 'openchore'
      app: 'openchore'
      podSelector: 'app.kubernetes.io/instance=openchore,app.kubernetes.io/name=openchore,app.kubernetes.io/controller=web'
      siteMonitor: 'http://openchore-web.openchore.svc.cluster.local:8080'
  - ESPHome:
      icon: 'mdi-home-automation'
      href: 'https://esphome.${DOMAIN_0}'
      namespace: 'esphome'
      app: 'esphome'
      siteMonitor: 'http://esphome.esphome.svc.cluster.local:6052'
  - Zigbee2MQTT:
      icon: 'mdi-zigbee'
      href: 'https://z2m.${DOMAIN_0}'
      namespace: 'zigbee2mqtt'
      app: 'zigbee2mqtt'
      siteMonitor: 'http://zigbee2mqtt.zigbee2mqtt.svc.cluster.local:8080'
  - Z-Wave JS UI:
      icon: 'mdi-waveform'
      href: 'https://zwave.${DOMAIN_0}'
      namespace: 'zwave-js-ui'
      app: 'zwave-js-ui'
      siteMonitor: 'http://zwave-js-ui.zwave-js-ui.svc.cluster.local:8091'
- Office:
  - Flatnotes:
      icon: 'sh-flatnotes.svg'
      href: 'https://docs.${DOMAIN_0}'
      siteMonitor: 'http://flatnotes.flatnotes.svc.cluster.local:8080'
      namespace: 'flatnotes'
      app: 'flatnotes'
      podSelector: 'app.kubernetes.io/instance=flatnotes,app.kubernetes.io/name=flatnotes'
- Finances:
  - SplitPro:
      icon: 'sh-splitpro.svg'
      href: 'https://split.${DOMAIN_0}'
      siteMonitor: 'http://splitpro.splitpro.svc.cluster.local:3000'
      namespace: 'splitpro'
      app: 'splitpro'
      podSelector: 'app.kubernetes.io/instance=splitpro,app.kubernetes.io/name=splitpro'
- Library:
  - Plex:
      icon: 'sh-plex.svg'
      href: 'https://plex.${DOMAIN_1}'
      siteMonitor: 'http://plex.plex.svc.cluster.local:32400'
      namespace: 'plex'
      app: 'plex'
      podSelector: 'app.kubernetes.io/instance=plex,app.kubernetes.io/name=plex,pod.name=main'
      widgets:
        - type: 'plex'
          fields: ["albums", "movies", "tv"]
          url: 'http://plex.plex.svc.cluster.local:32400'
          key: '{{HOMEPAGE_FILE_PLEX_KEY}}'
  - Romm:
      icon: 'sh-romm.svg'
      href: 'https://romm.${DOMAIN_1}'
      siteMonitor: 'http://romm.romm.svc.cluster.local:8080'
      namespace: 'romm'
      app: 'romm'
      podSelector: 'app.kubernetes.io/instance=romm,app.kubernetes.io/name=romm,app.kubernetes.io/component=romm'
      widgets:
        - type: 'romm'
          url: 'http://romm.romm.svc.cluster.local:8080'
  - Immich:
      icon: 'sh-immich.svg'
      href: 'https://immich.${DOMAIN_0}'
      siteMonitor: 'http://immich-server.immich.svc.cluster.local:2283'
      namespace: 'immich'
      app: 'immich'
      podSelector: 'app.kubernetes.io/instance=immich,app.kubernetes.io/name=immich,app.kubernetes.io/controller=server'
      widgets:
        - type: 'immich'
          url: 'http://immich-server.immich.svc.cluster.local:2283'
          key: '{{HOMEPAGE_FILE_IMMICH_KEY}}'
          version: 2
  - Grimmory:
      icon: 'sh-grimmory.svg'
      href: 'https://grimmory.${DOMAIN_1}'
      siteMonitor: 'http://grimmory.grimmory.svc.cluster.local:6060'
      podSelector: 'app.kubernetes.io/instance=grimmory,app.kubernetes.io/name=grimmory,app.kubernetes.io/controller=grimmory'
- Media Management:
  - Radarr:
      icon: 'sh-radarr.svg'
      href: 'https://radarr.${DOMAIN_1}'
      namespace: 'radarr'
      app: 'radarr'
      siteMonitor: 'http://radarr.radarr.svc.cluster.local:7878'
      widgets:
        - type: 'radarr'
          key: '{{HOMEPAGE_FILE_RADARR_KEY}}'
          url: 'http://radarr.radarr.svc.cluster.local:7878'
  - Sonarr:
      icon: 'sh-sonarr.svg'
      href: 'https://sonarr.${DOMAIN_1}'
      namespace: 'sonarr'
      app: 'sonarr'
      siteMonitor: 'http://sonarr.sonarr.svc.cluster.local:8989'
      widgets:
        - type: 'sonarr'
          key: '{{HOMEPAGE_FILE_SONARR_KEY}}'
          url: 'http://sonarr.sonarr.svc.cluster.local:8989'
  # - Lidarr:
  #     icon: 'sh-lidarr.svg'
  #     href: 'https://lidarr.${DOMAIN_1}'
  #     siteMonitor: 'http://lidarr.lidarr.svc.cluster.local:8686'
  - Seerr:
      icon: '/images/icons/seerr.png'
      href: 'https://${DOMAIN_1}'
      namespace: 'seerr'
      app: 'seerr'
      siteMonitor: 'http://seerr.seerr.svc.cluster.local:5055'
      widgets:
        - type: 'seerr'
          key: '{{HOMEPAGE_FILE_SEERR_KEY}}'
          url: 'http://seerr.seerr.svc.cluster.local:5055'
  - Maintainerr:
      icon: 'sh-maintainerr.svg'
      href: 'https://maintainerr.${DOMAIN_1}'
      namespace: 'maintainerr'
      app: 'maintainerr'
      siteMonitor: 'http://maintainerr.maintainerr.svc.cluster.local:6246'
  - Bazarr:
      icon: 'sh-bazarr.svg'
      href: 'https://bazarr.${DOMAIN_1}'
      namespace: 'bazarr'
      app: 'bazarr'
      siteMonitor: 'http://bazarr.bazarr.svc.cluster.local:6767'
- Tools:
  - Tracearr:
      icon: 'sh-tracearr.svg'
      href: 'https://tracearr.${DOMAIN_1}'
      siteMonitor: 'http://tracearr.tracearr.svc.cluster.local:3000'
      widgets:
        - type: tracearr
          url: 'http://tracearr.tracearr.svc.cluster.local:3000'
          key: '{{HOMEPAGE_FILE_TRACEARR_KEY}}'
  # - Watcharr:
  #     icon: 'sh-watcharr.webp'
  #     href: 'https://watch.${DOMAIN_1}'
  #     siteMonitor: 'http://watcharr.watcharr.svc.cluster.local:10684'
  # - Maloja:
  #     icon: 'sh-maloja.svg'
  #     href: 'https://maloja.${DOMAIN_1}'
  #     siteMonitor: 'http://maloja.maloja.svc.cluster.local:42010'
  # - Multi-Scrobbler:
  #     icon: 'sh-multi-scrobbler.svg'
  #     href: 'https://scrobbler.${DOMAIN_1}'
  #     siteMonitor: 'http://multi-scrobbler.multi-scrobbler.svc.cluster.local:9078'
  # TAB 4 - ROW 1
- Download Clients:
  - qBittorrent:
      icon: 'sh-qbittorrent.svg'
      href: 'https://qb1.${DOMAIN_1}'
      siteMonitor: 'http://qbittorrent-1.torrent.svc.cluster.local:8080'
      namespace: 'torrent'
      app: 'qbittorrent-1'
      podSelector: 'app.kubernetes.io/controller=qbittorrent-1,app.kubernetes.io/instance=qbittorrent-1,app.kubernetes.io/name=qbittorrent-1'
      widgets:
        - type: 'qbittorrent'
          url: 'http://qbittorrent-1.torrent.svc.cluster.local:8080'
          username: 'admin'
          password: '{{HOMEPAGE_FILE_QB_PASSWORD}}'
  - qBittorrent-2:
      icon: 'sh-qbittorrent.svg'
      href: 'https://qb2.${DOMAIN_1}'
      siteMonitor: 'http://qbittorrent-2.torrent.svc.cluster.local:8080'
      namespace: 'torrent'
      app: 'qbittorrent-2'
      podSelector: 'app.kubernetes.io/controller=qbittorrent-2,app.kubernetes.io/instance=qbittorrent-2,app.kubernetes.io/name=qbittorrent-2'
      widgets:
        - type: 'qbittorrent'
          url: 'http://qbittorrent-2.torrent.svc.cluster.local:8080'
          username: 'admin'
          password: '{{HOMEPAGE_FILE_QB_PASSWORD}}'
  - qBittorrent-3:
      icon: 'sh-qbittorrent.svg'
      href: 'https://qb3.${DOMAIN_1}'
      siteMonitor: 'http://qbittorrent-3.torrent.svc.cluster.local:8080'
      namespace: 'torrent'
      app: 'qbittorrent-3'
      podSelector: 'app.kubernetes.io/controller=qbittorrent-3,app.kubernetes.io/instance=qbittorrent-3,app.kubernetes.io/name=qbittorrent-3'
      widgets:
        - type: 'qbittorrent'
          url: 'http://qbittorrent-3.torrent.svc.cluster.local:8080'
          username: 'admin'
          password: '{{HOMEPAGE_FILE_QB_PASSWORD}}'
  - qBittorrent-4:
      icon: 'sh-qbittorrent.svg'
      href: 'https://qb4.${DOMAIN_1}'
      siteMonitor: 'http://qbittorrent-4.torrent.svc.cluster.local:8080'
      namespace: 'torrent'
      app: 'qbittorrent-4'
      podSelector: 'app.kubernetes.io/controller=qbittorrent-4,app.kubernetes.io/instance=qbittorrent-4,app.kubernetes.io/name=qbittorrent-4'
      widgets:
        - type: 'qbittorrent'
          url: 'http://qbittorrent-4.torrent.svc.cluster.local:8080'
          username: 'admin'
          password: '{{HOMEPAGE_FILE_QB_PASSWORD}}'
  - SABnzbd:
      icon: 'sh-sabnzbd.svg'
      href: 'https://sabnzbd.${DOMAIN_1}'
      siteMonitor: 'http://sabnzbd.sabnzbd.svc.cluster.local:8080'
      namespace: 'sabnzbd'
      app: 'sabnzbd'
      podSelector: 'app.kubernetes.io/instance=sabnzbd,app.kubernetes.io/name=sabnzbd,pod.name=main'
      widgets:
        - type: 'sabnzbd'
          url: 'http://sabnzbd.sabnzbd.svc.cluster.local:8080'
          key: '{{HOMEPAGE_FILE_SABNZBD_KEY}}'
- Download Tools:
  - Prowlarr:
      icon: 'sh-prowlarr.svg'
      href: 'https://prowlarr.${DOMAIN_1}'
      siteMonitor: 'http://prowlarr.prowlarr.svc.cluster.local:9696'
      namespace: 'prowlarr'
      app: 'prowlarr'
      podSelector: 'app.kubernetes.io/instance=prowlarr,app.kubernetes.io/name=prowlarr,pod.name=main'
      widgets:
        - type: 'prowlarr'
          url: 'http://prowlarr.prowlarr.svc.cluster.local:9696'
          key: '{{HOMEPAGE_FILE_PROWLARR_KEY}}'
  - Autobrr:
      icon: 'sh-autobrr.svg'
      href: 'https://autobrr.${DOMAIN_1}'
      siteMonitor: 'http://autobrr.autobrr.svc.cluster.local:7474'
      namespace: 'autobrr'
      app: 'autobrr'
      podSelector: 'app.kubernetes.io/instance=autobrr,app.kubernetes.io/name=autobrr,pod.name=main'
      widgets:
        - type: 'autobrr'
          url: 'http://autobrr.autobrr.svc.cluster.local:7474'
          key: '{{HOMEPAGE_FILE_AUTOBRR_KEY}}'
  - qui:
      icon: 'sh-qui.svg'
      href: 'https://qui.${DOMAIN_1}'
      siteMonitor: 'http://qui.torrent.svc.cluster.local:7476'
      namespace: 'torrent'
      app: 'qui'
      podSelector: 'app.kubernetes.io/instance=qui,app.kubernetes.io/name=qui,pod.name=main'
