# yaml-language-server: $schema=https://www.schemastore.org/any.json
---
title: 'root:freeman'
favicon: '/images/favicon.png'
providers:
  openweathermap: 'openweathermapapikey'
  weatherapi: 'weatherapiapikey'
headerStyle: 'clean'
iconStyle: 'theme'
target: '_blank'
language: 'en'
quicklaunch:
    hideInternetSearch: 'true'
    provider: 'duckduckgo'
statusStyle: 'dot'
hideVersion: 'true'
hideErrors: 'true'
useEqualHeights: 'true'
layout:
  # TAB 1
  Core:
    tab: 'System'
    icon: 'mdi-server'
    style: 'row'
    columns: '8'
  Bookmarks:
    tab: 'System'
  Server:
    tab: 'System'
  Forums:
    tab: 'System'
  # TAB 2
  Services:
    tab: 'Services'
    icon: 'mdi-apps'
    style: 'row'
    columns: '8'
  Domotics:
    tab: 'Services'
    icon: 'mdi-home-automation'
    style: 'row'
    columns: '8'
  Accounting:
    tab: 'Services'
  Communication:
    tab: 'Services'
  Social Media:
    tab: 'Services'
  Resources:
    tab: 'Services'
  Gaming:
    tab: 'Services'
  Boards:
    tab: 'Services'
  # TAB 3
  Media:
    tab: 'Media'
    icon: 'mdi-bookshelf'
    style: row
    columns: '8'
  Usenet:
    tab: 'Media'
    icon: 'mdi-newspaper-variant-multiple'
  Torrent/EN:
    tab: 'Media'
    icon: 'mdi-download-network'
  Torrent/FR:
    tab: 'Media'
    icon: 'mdi-download-network'
  Direct Download:
    tab: 'Media'
    icon: 'mdi-cloud-download'
