# yaml-language-server: $schema=https://www.schemastore.org/any.json
---
title: 'root:freeman'
favicon: '/images/favicon.png'
providers:
  openweathermap: 'openweathermapapikey'
  weatherapi: 'weatherapiapikey'
headerStyle: 'clean'
iconStyle: 'theme'
target: '_blank'
language: 'en'
quicklaunch:
    searchDescriptions: 'false'
    hideInternetSearch: 'true'
    provider: 'duckduckgo'
statusStyle: 'dot'
hideVersion: 'true'
hideErrors: 'true'
useEqualHeights: 'true'
layout:
  # TAB 1
  Servers:
    tab: 'Home'
    icon: 'mdi-server-network'
    style: 'row'
    columns: '4'
  Management:
    tab: 'Home'
    icon: 'mdi-gauge'
    style: 'row'
    columns: '3'
  Network:
    tab: 'Home'
    icon: 'mdi-wan'
    style: 'row'
    columns: '5'
  Bookmarks:
    tab: 'Home'
  Server:
    tab: 'Home'
  Forums:
    tab: 'Home'
  # TAB 2
  Everyday Life:
    tab: 'Applications'
    icon: 'mdi-leaf'
    style: row
    columns: '5'
  Office:
    tab: 'Applications'
    icon: 'mdi-text-box'
    style: 'row'
    columns: '5'
  Finances:
    tab: 'Applications'
    icon: 'mdi-finance'
    style: 'row'
    columns: '5'
  Broadcasting:
    tab: 'Applications'
    icon: 'mdi-broadcast'
    style: 'row'
    columns: '4'
  File Sharing:
    tab: 'Applications'
    icon: 'mdi-share-variant'
    style: 'row'
    columns: '4'
  Data Processing:
    tab: 'Applications'
    icon: 'mdi-database'
    style: 'row'
    columns: '3'
  Accounting:
    tab: 'Applications'
  Communication:
    tab: 'Applications'
  Social Media:
    tab: 'Applications'
  # TAB 3
  Library:
    tab: 'Multimedia'
    icon: 'mdi-bookshelf'
    style: 'row'
    columns: '3'
  Media Management:
    tab: 'Multimedia'
    icon: 'mdi-multimedia'
    style: 'row'
    columns: '4'
  Tools:
    tab: 'Multimedia'
    icon: 'mdi-toolbox'
    style: 'row'
    columns: '5'
  Resources:
    tab: 'Multimedia'
  Gaming:
    tab: 'Multimedia'
  Boards:
    tab: 'Multimedia'
  # TAB 4
  Download Clients:
    tab: 'Download'
    icon: 'mdi-cloud-download'
    style: 'row'
    columns: '4'
  Media Downloaders:
    tab: 'Download'
    icon: 'mdi-play-network'
    style: 'row'
    columns: '5'
  Download Tools:
    tab: 'Download'
    icon: 'mdi-cog-transfer'
    style: 'row'
    columns: '4'
  Usenet:
    tab: 'Download'
  Torrent/EN:
    tab: 'Download'
  Torrent/FR:
    tab: 'Download'
  Direct Download:
    tab: 'Download'
