---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gluetun-delta
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: gluetun-router
  interval: 1h
  path: kubernetes/components/vpn/instance
  postBuild:
    substitute:
      APP: *app
      VPN_INSTANCE: "4"
      VPN_PROXIES_ENABLED: "true"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: gluetun
  timeout: 5m
  wait: true
