---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app shelfmark
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/common/app
    - ../../../../components/gluetun
    - ../../../../components/homepage
    - ../../../../components/volsync
  dependsOn:
    - name: byparr
    - name: envoy-gateway-config
    - name: external-secrets-store
    - name: gluetun-echo
    - name: openebs
    - name: rook-ceph-cluster
    - name: volsync
  interval: 1h
  path: kubernetes/apps/media/shelfmark/app
  postBuild:
    substitute:
      APP: *app
      GLUETUN_GATEWAY_ID: "5"
      GLUETUN_GATEWAY_NAME: gluetun-echo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: *app
  timeout: 5m
  wait: true
