apiVersion: batch/v1
kind: CronJob
metadata:
  name: &name volsync-queue
  namespace: volsync
spec:
  suspend: false
  schedule: "0 5 * * *"
  timeZone: America/Toronto
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: *name
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumes:
            - name: script
              configMap:
                name: volsync-queue-script
                defaultMode: 0555
          containers:
            - name: queue
              image: bitnami/kubectl@sha256:b29d8c1665b70817259ceecaea16ab27aab6368b48daf485d19436c809067492
              # env:
              #   - name: VOLSYNC_QUEUE_EXCLUDE_TARGETS
              #     value: plex/plex-data
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
                runAsNonRoot: true
              volumeMounts:
                - name: script
                  mountPath: /scripts
                  readOnly: true
              command: ["/bin/sh", "-eu", "/scripts/volsync-queue.sh"]
