apiVersion: batch/v1
kind: CronJob
metadata:
  name: &name volsync-queue
spec:
  suspend: false
  schedule: "0 5 * * *"
  timeZone: America/Toronto
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: *name
          restartPolicy: Never
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumes:
            - name: script
              configMap:
                name: volsync-queue-script
                defaultMode: 0555
          containers:
            - name: queue
              image: bitnami/kubectl@sha256:95de17e6eb92da83a58c90a9df0c4cede634f898d2e6b92ea04f4a6ee6ace08d
              # env:
              #   - name: VOLSYNC_QUEUE_EXCLUDE_TARGETS
              #     value: plex/plex-data
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
                runAsNonRoot: true
              volumeMounts:
                - name: script
                  mountPath: /scripts
                  readOnly: true
              command: ["/bin/sh", "-eu", "/scripts/volsync-queue.sh"]
