---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/toolhive.stacklok.dev/mcpexternalauthconfig_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPExternalAuthConfig
metadata:
  name: poznote-mcp-auth
spec:
  type: headerInjection
  headerInjection:
    headerName: Authorization
    valueSecretRef:
      name: poznote-mcp-secret
      key: POZNOTE_MCP_AUTHORIZATION
