---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret poznote-mcp-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    template:
      mergePolicy: Merge
      data:
        POZNOTE_MCP_AUTHORIZATION: 'Bearer {{ .POZNOTE_MCP_AUTH_TOKEN }}'
  data:
    - secretKey: POZNOTE_MCP_AUTH_TOKEN
      remoteRef:
        key: poznote
        property: POZNOTE_MCP_AUTH_TOKEN
