---
id: tv-vault
name: TV-Vault
description: "TV-Vault is a private torrent tracker for classic TV shows."
language: en-US
type: private
encoding: UTF-8
links:
  - https://tv-vault.me/

caps:
  categorymappings:
    - {id: 1, cat: TV, desc: "TV"}
    - {id: 2, cat: Movies, desc: "Movies"}
    - {id: 3, cat: TV/HD, desc: "TV HD"}
    - {id: 4, cat: TV/SD, desc: "TV SD"}

  modes:
    search: [q]
    tv-search: [q, season, ep, imdbid]
    movie-search: [q, imdbid]

settings:
  - name: username
    type: text
    label: Username
  - name: password
    type: password
    label: Password

login:
  path: login.php
  method: post
  inputs:
    username: "{{ .Config.username }}"
    password: "{{ .Config.password }}"
    keeplogged: 1
    login: "Log In!"
  error:
    - selector: form#loginform > span.warning
    - selector: form#loginform
      message:
        text: "Login page detected at {{ .Config.sitelink }}."
  test:
    path: index.php
    selector: a[href^="logout.php"]

search:
  paths:
    - path: torrents.php

  keywordsfilters:
    - name: re_replace
      args: ['(?i)[SE]\d\d', '']
    - name: trim

  inputs:
    $raw: "{{ range .Categories }}filter_cat[{{.}}]=1&{{end}}"
    order_by: s3
    order_way: DESC
    disablegrouping: 1
    action: "{{ if .Query.IMDBID }}advanced{{ else }}{{ end }}"
    imdbid: "{{ .Query.IMDBID }}"
    searchstr: "{{ if .Query.IMDBID }}{{ else }}{{ .Keywords }}{{ end }}"

  rows:
    selector: table.torrent_table > tbody > tr.torrent:has(a[href^="torrents.php?id="])

  fields:
    _torrentid:
      selector: a[href^="torrents.php?id="]
      attribute: href
      filters:
        - name: regexp
          args: 'id=(\d+)'
    _title:
      selector: a[href^="torrents.php?id="]
    description:
      selector: td:nth-child(2)
      remove: a[href^="torrents.php?id="], a[href^="torrents.php?action=download"], strong.freeleech_normal, span, img
      filters:
        - name: replace
          args: ['\n', ' ']
        - name: trim
    title:
      text: "{{ .Result._title }} {{ .Result.description }}"
      filters:
        - name: trim
    details:
      selector: a[href^="torrents.php?id="]
      attribute: href
    download:
      text: "{{ .Config.sitelink }}torrents.php?action=download&id={{ .Result._torrentid }}"
    files:
      selector: td:nth-child(3)
    date:
      selector: td:nth-child(4)
      filters:
        - name: timeago
    size:
      selector: td:nth-child(5)
    grabs:
      selector: td:nth-child(6)
    seeders:
      selector: td:nth-child(7)
    leechers:
      selector: td:nth-child(8)
    downloadvolumefactor:
      case:
        strong.freeleech_normal: 0
        "*": 1
    uploadvolumefactor:
      text: 1
    minimumratio:
      text: 1
    minimumseedtime:
      text: 0
