---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: alloy
spec:
  interval: 5m
  provider: generic
  ref:
    tag: 1.10.0
  url: oci://ghcr.io/home-operations/charts-mirror/alloy
