---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app node-network-operator
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/common/system
  dependsOn:
    - name: cert-manager-issuers
    - name: cilium
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: kube-system
    - apiVersion: apps/v1
      kind: Deployment
      name: node-network-operator-cluster
      namespace: kube-system
    - apiVersion: apps/v1
      kind: DaemonSet
      name: node-network-operator-node
      namespace: kube-system
  interval: 1h
  path: kubernetes/apps/system/node-network-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kube-system
  timeout: 5m
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-network-operator-config
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: node-network-operator
      app.kubernetes.io/component: config
  components:
    - ../../../../components/common/system
  dependsOn:
    - name: node-network-operator
  healthCheckExprs:
    - apiVersion: nodenetworkoperator.soliddowant.dev/v1alpha1
      kind: Link
      failed: status.conditions.exists(e, e.type == 'Ready' && e.status == 'False')
      current: status.conditions.exists(e, e.type == 'Ready' && e.status == 'True')
  interval: 1h
  path: kubernetes/apps/system/node-network-operator/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kube-system
  timeout: 5m
  wait: true
