# yaml-language-server: $schema=https://www.schemastore.org/any.json
tunnel: "6556b332-8538-4cba-b1e3-a78e8338b508"
credentials-file: /etc/cloudflared/cloudflare-tunnel.json
ingress:
  - hostname: "*.${DOMAIN_0}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_0}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - hostname: "*.${DOMAIN_1}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_1}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - hostname: "*.${DOMAIN_2}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_2}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - service: http_status:404
