---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret karakeep-app-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: karakeep
        property: NEXTAUTH_SECRET
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: karakeep
        property: OAUTH_CLIENT_SECRET
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: karakeep
        property: OPENAI_API_KEY
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret karakeep-meilisearch-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
  data:
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: karakeep
        property: MEILI_MASTER_KEY
