---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: services
spec:
  blocks:
    - start: 10.0.20.2
      stop: 10.0.20.254
  serviceSelector:
    matchLabels:
      network.k8s-gitops.io/lb-pool: services
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: dmz
spec:
  blocks:
    - start: 10.0.25.2
      stop: 10.0.25.254
  serviceSelector:
    matchLabels:
      network.k8s-gitops.io/lb-pool: dmz
