apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name cloudnative-pg
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *name
  values:
    crds:
      create: true
    replicaCount: 2
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
