---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qbittorrent-3
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../../components/common/system
    - ../../../../../components/envoy-oidc
    - ../../../../../components/volsync
    - ../../../../../components/vpn
  dependsOn:
    - name: gluetun-bravo
    - name: torrent
  interval: 1h
  path: kubernetes/apps/media/torrent/qbittorrent-3/app
  postBuild:
    substitute:
      APP: *app
      VPN_GATEWAY_NAME: gluetun-bravo
      VPN_GATEWAY_ID: "2"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: torrent
  timeout: 5m
  wait: true
