---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: ${APP}-dragonfly
spec:
  image: ghcr.io/dragonflydb/dragonfly:latest@sha256:18228a84e2305d60de390f972f9622ec252120834b22c12b9e5025144b0b37fe
  replicas: 1
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 999
  env:
    - name: MAX_MEMORY
      valueFrom:
        resourceFieldRef:
          resource: limits.memory
          divisor: 1Mi
  args:
    - --maxmemory=512Mi
    - --proactor_threads=1
    - --cluster_mode=emulated
    - --default_lua_flags=allow-undeclared-keys
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/part-of: ${APP}-dragonfly
