---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: ${APP}-dragonfly-secret
spec:
  allowRepeat: true
  digits: 10
  length: 64
  noUpper: false
  secretKeys: ["password"]
  symbols: 0
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-dragonfly-secret
spec:
  refreshPolicy: CreatedOnce
  target:
    name: ${APP}-dragonfly-secret
    template:
      engineVersion: v2
      data:
        REDIS_URL: 'redis://:{{ .password }}@${APP}-dragonfly.${APP}.svc.cluster.local:6379/0'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: ${APP}-dragonfly-secret
