---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: maintainerr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      maintainerr:
        containers:
          app:
            image:
              repository: ghcr.io/maintainerr/maintainerr
              tag: 3.20.0@sha256:049db172a9b98998480e48b4061c51c4b90adfb18158863cb9c8f65f0cfba4f3
            probes:
              liveness:
                enabled: true
                type: HTTP
                path: /api/health/live
              readiness:
                enabled: true
                type: HTTP
                path: /api/health/ready
            resources:
              requests:
                cpu: 25m
                memory: 256Mi
              limits:
                memory: 512Mi
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
    persistence:
      data:
        existingClaim: maintainerr-data
        globalMounts:
          - path: /opt/data
      logs:
        type: emptyDir
        globalMounts:
          - path: /opt/data/logs
    route:
      app:
        hostnames: ['maintainerr.${DOMAIN_1}']
        parentRefs:
          - name: envoy-internal
            namespace: envoy-gateway
            sectionName: https
    service:
      app:
        ports:
          http:
            port: 6246
