apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/common/domain
configMapGenerator:
  - name: domain
    literals: [DOMAIN=system]
generatorOptions:
  annotations:
    config.kubernetes.io/local-config: "true"
labels:
  - pairs:
      domain: system
namespace: flux-system
resources:
  - alloy/ks.yaml
  - cert-manager/ks.yaml
  - cilium/ks.yaml
  - csi-driver-nfs/ks.yaml
  - descheduler/ks.yaml
  - flux-system
  - k8tz/ks.yaml
  - kube-prometheus-stack/ks.yaml
  - kubelet-csr-approver/ks.yaml
  - loki/ks.yaml
  - metrics-server/ks.yaml
  - multus/ks.yaml
  - node-network-operator/ks.yaml
  - openebs/ks.yaml
  - reloader/ks.yaml
  - rook-ceph/ks.yaml
  - snapshot-controller/ks.yaml
  - spegel/ks.yaml
  - tuppr/ks.yaml
  - whereabouts/ks.yaml
