---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: splitpro
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      splitpro:
        initContainers:
          db-wait:
            image:
              repository: postgres
              tag: "18.4-alpine3.23@sha256:996d0920e4ff9df1fc19dacb904492f3c1ec0ec1cc338f0ad7123be7731c5f5e"
            command: ["/bin/sh", "-ec"]
            args: ["until pg_isready -q -h ${APP}-cnpg-rw -p 5432 -U postgres -d postgres; do sleep 2; done"]
            securityContext: &securityContext
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
        containers:
          app:
            image:
              repository: ossapps/splitpro
              tag: v2.1.4@sha256:25897807deb136c5b75ed6243594da4641e4a7d98de8b45a516e2c2c92e00cdf
            env:
              PORT: &httpPort 3000
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: splitpro-cnpg-app
                    key: fqdn-uri
              DEFAULT_HOMEPAGE: /balances
              DISABLE_EMAIL_SIGNUP: true
              ENABLE_SENDING_INVITES: true
              FROM_EMAIL: id@${DOMAIN_0}
              EMAIL_SERVER_PORT: 587
              EMAIL_SERVER_HOST: ${SMTP_HOST_0}
              EMAIL_SERVER_USER: ${SMTP_USERNAME_0}
              NEXTAUTH_URL: https://split.${DOMAIN_0}
              OIDC_NAME: Freeman ID
              OIDC_CLIENT_ID: 31e06d58-9a6b-4e3f-8e10-819f5ab1e2fd
              OIDC_WELL_KNOWN_URL: https://id.${DOMAIN_0}/.well-known/openid-configuration
              OIDC_ALLOW_DANGEROUS_EMAIL_LINKING: true
            envFrom:
              - secretRef:
                  name: splitpro-app-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 25m
                memory: 256Mi
              limits:
                memory: 512Mi
            securityContext: *securityContext
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
    persistence:
      data:
        existingClaim: splitpro-data
        globalMounts:
          - path: /app/uploads
    route:
      app:
        hostnames: ['split.${DOMAIN_0}']
        parentRefs:
          - name: envoy-external
            namespace: envoy-gateway
            sectionName: https
    service:
      app:
        ports:
          http:
            port: *httpPort
