---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-app-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-webui-app-secret
  dataFrom:
    - extract:
        key: open-webui
  data:
    - secretKey: OPENAI_API_KEYS
      remoteRef:
        key: litellm
        property: LITELLM_MASTER_KEY
