---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: ${APP}-oidc
  labels:
    app.kubernetes.io/component: envoy-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: ${APP}
  oidc:
    provider:
      issuer: https://id.${DOMAIN_0}
    clientIDRef:
      name: ${APP}-oidc-secret
    clientSecret:
      name: ${APP}-oidc-secret
    forwardAccessToken: ${ENVOY_OIDC_FORWARD_ACCESS_TOKEN:=true}
    cookieNames:
      idToken: ${APP}-oidc-token
    scopes: [profile,email,groups]
    redirectURL: https://oidc-placeholder.invalid/oauth2/callback
  jwt:
    providers:
      - name: pocketid
        issuer: https://id.${DOMAIN_0}
        remoteJWKS:
          uri: https://id.${DOMAIN_0}/.well-known/jwks.json
        extractFrom:
          cookies: ['${APP}-oidc-token']
  authorization:
    defaultAction: Deny
    rules:
      - name: allow-oidc-groups
        action: Allow
        principal:
          jwt:
            provider: pocketid
            claims:
              - name: groups
                valueType: StringArray
                values: ['${ENVOY_OIDC_GROUP:=admin}']
