---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app intel-gpu-driver
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/common/system
  dependsOn:
    - name: cilium
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: *app
      namespace: kube-system
  interval: 1h
  path: kubernetes/apps/system/intel-gpu-driver/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kube-system
  timeout: 5m
  wait: true
