---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app mealie
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/common/app
    - ../../../../components/cnpg
    - ../../../../components/volsync
  dependsOn:
    - name: cloudnative-pg
    - name: envoy-gateway-config
    - name: external-secrets-store
    - name: openebs
    - name: rook-ceph-cluster
    - name: volsync
  interval: 1h
  path: kubernetes/apps/services/mealie/app
  postBuild:
    substitute:
      APP: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: *app
  timeout: 5m
  wait: true
