# yaml-language-server: $schema=https://taskfile.dev/schema.json
---
version: "3"

tasks:

  pvc:mount:
    desc: Mount a PVC in a temporary BusyBox pod (PVC=<pvc-name> [NS=<namespace>] [RUN_AS_USER=568] [RUN_AS_GROUP=568])
    silent: true
    cmd: >-
      PVC="{{.PVC}}" NS="{{.NS | default ""}}" RUN_AS_USER="{{.RUN_AS_USER | default "568"}}" RUN_AS_GROUP="{{.RUN_AS_GROUP | default "568"}}" POD="pvc-mount-{{.PVC}}"; [ -n "$NS" ] || NS="$(kubectl get pvc -A --field-selector metadata.name="$PVC" -o jsonpath='{.items[0].metadata.namespace}')"; [ -n "$NS" ] || { echo "PVC '$PVC' not found"; exit 1; }; export PVC POD RUN_AS_USER RUN_AS_GROUP; envsubst < .taskfiles/kubernetes/templates/pvc-mount.yaml | kubectl -n "$NS" apply -f - && kubectl -n "$NS" wait pod/"$POD" --for=condition=Ready --timeout=2m && kubectl -n "$NS" exec -it "$POD" -- sh
    requires:
      vars: [PVC]

  pvc:unmount:
    desc: Delete the temporary BusyBox PVC pod (PVC=<pvc-name> [NS=<namespace>])
    silent: true
    cmd: >-
      PVC="{{.PVC}}" NS="{{.NS | default ""}}" POD="pvc-mount-{{.PVC}}"; [ -n "$NS" ] || NS="$(kubectl get pod -A --field-selector metadata.name="$POD" -o jsonpath='{.items[0].metadata.namespace}')"; [ -n "$NS" ] || { echo "pod '$POD' not found"; exit 1; }; kubectl -n "$NS" delete pod "$POD" --ignore-not-found
    requires:
      vars: [PVC]

  secrets:list:
    desc: List ignored app files
    silent: true
    cmd: |-
      while IFS= read -r path || [ -n "$path" ]; do
        case "$path" in /kubernetes/apps/*/*/*) ;; *) continue ;; esac
        externalsecret_path=".${path%/app/*}/app/externalsecret.yaml"
        [ -f "$externalsecret_path" ] || continue
        yq --no-doc --output-format=tsv "
          .spec.data[]?
          | select(.secretKey == \"${path##*/}\" and .remoteRef.key)
          | [\"$(basename "${path%/app/*}")\", .remoteRef.key, (.remoteRef.property // .secretKey), \".$path\"]
        " "$externalsecret_path"
      done < .gitignore
    preconditions:
      - sh: test -f .gitignore
      - sh: which yq

  secrets:push:
    desc: Push ignored app files to 1Password
    silent: true
    cmd: |-
      task kubernetes:secrets:list \
      | while IFS="$(printf '\t')" read -r app item file_name file_path; do
          field_name="$(printf '%s' "$file_name" | sed 's/[.=\\]/\\&/g')"
          op item edit "$item" "$field_name[file]=$file_path" --vault "{{.OP_VAULT}}" < /dev/tty > /dev/null || exit 1
          echo "$app/$file_name -> $item"
        done
    preconditions:
      - sh: test -f .gitignore
      - sh: op user get --me
      - sh: which yq
