---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app romm
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      romm:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/rommapp/romm
              tag: 4.8.1@sha256:2b7a1714b287f69b081ad2a63bb8c2fa673666a17b2f21322b580b0cd51cb266
            env:
              DB_HOST: romm-cnpg-rw
              DB_PORT: 5432
              DB_USER: *app
              DB_PASSWD_FILE: /secrets/cnpg/password
              REDIS_HOST: romm-dragonfly
              REDIS_PASSWORD_FILE: /secrets/dragonfly/password
              ROMM_DB_DRIVER: postgresql
              ROMM_AUTH_SECRET_KEY_FILE: /secrets/ROMM_AUTH_SECRET_KEY
              ENABLE_SCHEDULED_CONVERT_IMAGES_TO_WEBP: true
              ENABLE_SCHEDULED_RETROACHIEVEMENTS_PROGRESS_SYNC: true
              HASHEOUS_API_ENABLED: true
              DISABLE_USERPASS_LOGIN: true
              OIDC_ENABLED: true
              OIDC_PROVIDER: pocket-id
              OIDC_CLIENT_ID: f9c92072-e9cb-4fc6-a2de-458d4eaa2533
              OIDC_CLIENT_SECRET_FILE: /secrets/OIDC_CLIENT_SECRET
              OIDC_SERVER_APPLICATION_URL: https://id.${DOMAIN_0}
              OIDC_REDIRECT_URI: https://romm.${DOMAIN_1}/api/oauth/openid
              RETROACHIEVEMENTS_API_KEY_FILE: /secrets/RETROACHIEVEMENTS_API_KEY
            probes:
              liveness: &probe
                custom: true
                spec:
                  httpGet:
                    path: /api/heartbeat
                    port: &httpPort 8080
              readiness: *probe
            resources:
              requests: { cpu: 25m, memory: 512Mi }
              limits: { cpu: '18', memory: 64Gi }
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile:
              type: RuntimeDefault
          automountServiceAccountToken: false
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: romm-data
        globalMounts:
          - path: /romm/config
            subPath: config
          - path: /romm/assets
            subPath: assets
          - path: /romm/resources
            subPath: resources
      media:
        type: custom
        volumeSpec:
          csi:
            driver: nfs.csi.k8s.io
            volumeAttributes:
              server: 10.0.10.15
              share: /mnt/eden/media
        globalMounts:
          - path: /romm/library/games
            subPath: library/games
      launchbox:
        type: custom
        volumeSpec:
          csi:
            driver: nfs.csi.k8s.io
            volumeAttributes:
              server: 10.0.10.15
              share: /mnt/eden/backups
        advancedMounts:
          romm:
            app:
              - path: /romm/launchbox
                subPath: launchbox
              - path: /romm/library/Images
                subPath: launchbox/Images
              - path: /romm/library/Manuals
                subPath: launchbox/Manuals
              - path: /romm/library/Videos
                subPath: launchbox/Videos
      config:
        type: configMap
        name: romm-config
        globalMounts:
          - path: /romm/config/config.yml
            subPath: config.yml
            readOnly: true
      secrets:
        type: custom
        globalMounts:
          - path: /secrets
            readOnly: true
        volumeSpec:
          projected:
            sources:
              - secret:
                  name: romm-cnpg-app
                  items:
                    - key: password
                      path: cnpg/password
              - secret:
                  name: romm-dragonfly-secret
                  items:
                    - key: password
                      path: dragonfly/password
              - secret:
                  name: romm-app-secret
      nginx:
        type: emptyDir
        globalMounts:
          - path: /etc/nginx/conf.d
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
    route:
      app:
        hostnames: ['romm.${DOMAIN_1}']
        parentRefs:
          - name: envoy-internal
            namespace: envoy-gateway
            sectionName: https
    service:
      app:
        controller: *app
        ports:
          http:
            port: *httpPort
