---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret home-assistant-app-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        secrets.yaml: |
          home_assistant_url: {{ .HOME_ASSISTANT_URL | quote }}
          oidc_discovery_url: {{ .OIDC_DISCOVERY_URL | quote }}
          oidc_client_secret: {{ .OIDC_CLIENT_SECRET | quote }}
          recorder_db_url: {{ .RECORDER_DB_URI | quote }}
  dataFrom:
    - extract:
        key: home-assistant
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret git-sync-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
  data:
    - secretKey: HOME_ASSISTANT_API_TOKEN_GIT_SYNC
      remoteRef:
        key: home-assistant
        property: HOME_ASSISTANT_API_TOKEN_GIT_SYNC
