---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret envoy-oidc-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  dataFrom:
    - extract:
        key: envoy-gateway
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        client-id: "{{ .OAUTH_CLIENT_ID }}"
        client-secret: "{{ .OAUTH_CLIENT_SECRET }}"
