---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: rook-ceph-dashboard-oidc
  labels:
    app.kubernetes.io/component: envoy-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: rook-ceph-dashboard
  oidc:
    provider:
      issuer: "https://id.${DOMAIN_0}"
    clientIDRef:
      name: &secret envoy-oidc-secret
    clientSecret:
      name: *secret
    forwardAccessToken: true
    cookieNames:
      idToken: &oidcToken pocketid-token
    scopes: [profile,email,groups]
    redirectURL: "https://ceph.${DOMAIN_0}/oauth2/callback"
  jwt:
    providers:
      - name: &oidcProvider pocketid
        issuer: "https://id.${DOMAIN_0}"
        remoteJWKS:
          uri: "https://id.${DOMAIN_0}/.well-known/jwks.json"
        extractFrom:
          cookies: [*oidcToken]
  authorization:
    defaultAction: Deny
    rules:
      - name: allow-oidc-groups
        action: Allow
        principal:
          jwt:
            provider: *oidcProvider
            claims:
              - name: groups
                valueType: StringArray
                values: [admin]
