---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
spec:
  endpoints:
    - dnsName: external.${DOMAIN_0}
      recordType: CNAME
      targets: [6556b332-8538-4cba-b1e3-a78e8338b508.cfargotunnel.com]
