---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/externaldns.k8s.io/dnsendpoint_v1alpha1.json
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
spec:
  endpoints:
    - dnsName: external.${DOMAIN_0}
      recordType: CNAME
      targets: [dd243103-136c-426f-8342-00923c663d2e.cfargotunnel.com]
---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
tunnel: "83cb3785-04d0-45e3-99ad-1e4d3da99979"
credentials-file: /etc/cloudflared/cloudflare-tunnel.json
ingress:
  - hostname: "*.${DOMAIN_0}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_0}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - hostname: "*.${DOMAIN_1}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_1}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - hostname: "*.${DOMAIN_2}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_2}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - service: http_status:404
spec:
  endpoints:
    - targets:
        - dd243103-136c-426f-8342-00923c663d2e.cfargotunnel.com
---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
tunnel: "8340d998-b81f-4f67-b619-407758e4dec4"
credentials-file: /etc/cloudflared/cloudflare-tunnel.json
ingress:
  - hostname: "*.${DOMAIN_0}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_0}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - hostname: "*.${DOMAIN_1}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_1}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - hostname: "*.${DOMAIN_2}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_2}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - service: http_status:404
spec:
  endpoints:
    - targets:
        - dd243103-136c-426f-8342-00923c663d2e.cfargotunnel.com
---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
tunnel: "924ac253-0e52-4b02-b366-fea391f2a46d"
credentials-file: /etc/cloudflared/cloudflare-tunnel.json
ingress:
  - hostname: "*.${DOMAIN_0}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_0}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - hostname: "*.${DOMAIN_1}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_1}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - hostname: "*.${DOMAIN_2}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_2}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - service: http_status:404
spec:
  endpoints:
    - targets:
        - dd243103-136c-426f-8342-00923c663d2e.cfargotunnel.com
---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
tunnel: "dd243103-136c-426f-8342-00923c663d2e"
credentials-file: /etc/cloudflared/cloudflare-tunnel.json
ingress:
  - hostname: "*.${DOMAIN_0}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_0}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - hostname: "*.${DOMAIN_1}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_1}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - hostname: "*.${DOMAIN_2}"
    originRequest:
      http2Origin: true
      originServerName: external.${DOMAIN_2}
    service: https://envoy-external.envoy-gateway.svc.cluster.local:443
  - service: http_status:404
