---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret cloudflared-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        e677e019-4baa-49f1-9e0a-8b3b6f481405.json: |-
          {{- $token := .TUNNEL_TOKEN | b64dec | fromJson -}}
          {
            "AccountTag": "{{ $token.a }}",
            "TunnelID": "{{ $token.t }}",
            "TunnelSecret": "{{ $token.s }}"
          }
  dataFrom:
    - extract:
        key: cloudflared
