---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret cloudflared-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
  data:
    - secretKey: cloudflare-tunnel.json
      remoteRef:
        key: cloudflared
        property: cloudflare-tunnel.json
