# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app reloader
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: *app
  values:
    fullnameOverride: *app
    reloader:
      autoReloadAll: true
      ignoreNamespaces: kube-system,rook-ceph,openebs,snapshot-controller,flux-system,external-secrets,cert-manager,cloudnative-pg,dragonfly,volsync,reloader,system-upgrade
      readOnlyRootFileSystem: true
      deployment:
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: true
      podMonitor:
        enabled: true
