---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret gluetun-alfa-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        GLUETUN_API_KEY: "{{ .ALFA_GLUETUN_API_KEY }}"
        config.toml: |
          [[roles]]
          name = "port-forward"
          routes = ["GET /v1/portforward"]
          auth = "apikey"
          apikey = "{{ .ALFA_GLUETUN_API_KEY }}"
        vpn_service_provider: "{{ .VPN_SERVICE_PROVIDER_0 }}"
        wireguard_private_key: "{{ .ALFA_WIREGUARD_PRIVATE_KEY }}"
      mergePolicy: Replace
  dataFrom:
    - extract:
        key: gluetun
