---
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMVirtualKey
metadata:
  name: zed
spec:
  keyAlias: Zed
  models: [chatgpt/gpt-6-astra, chatgpt/gpt-6-luna, chatgpt/gpt-6-sol]
  proxyRef: litellm
  secretKey: api-key
  secretName: litellm-zed-secret
  teamID: admin
  userID: freeman
