---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret ${APP}-secret
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *secret
    template:
      engineVersion: v2
      data:
        config.toml: |
          [[roles]]
          name = "port-forward"
          routes = ["GET /v1/portforward"]
          auth = "apikey"
          apikey = "{{ .TOKEN }}"
        GLUETUN_API_KEY: '{{ .TOKEN }}'
        VPN_PORT_FORWARDING_PROVIDER: '{{ index . (printf "%s_VPN_SERVICE_PROVIDER" (replace "-" "_" (upper "${APP}"))) }}'
        wg0.conf: |
          [Interface]
          PrivateKey = {{ index . (printf "%s_WIREGUARD_PRIVATE_KEY" (replace "-" "_" (upper "${APP}"))) }}
          Address = {{ index . (printf "%s_WIREGUARD_ADDRESSES" (replace "-" "_" (upper "${APP}"))) }}

          [Peer]
          PublicKey = {{ index . (printf "%s_WIREGUARD_PUBLIC_KEY" (replace "-" "_" (upper "${APP}"))) }}
          Endpoint = {{ index . (printf "%s_WIREGUARD_ENDPOINT_IP" (replace "-" "_" (upper "${APP}"))) }}:{{ index . (printf "%s_WIREGUARD_ENDPOINT_PORT" (replace "-" "_" (upper "${APP}"))) }}
      mergePolicy: Replace
  dataFrom:
    - extract:
        key: gluetun
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: gluetun-token
---
# yaml-language-server: $schema=https://www.schemastore.org/any.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &agentSecret ${APP}-agent
spec:
  refreshPolicy: OnChange
  target:
    name: *agentSecret
    template:
      engineVersion: v2
      data:
        AGENT_TOKEN: '{{ .TOKEN }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: ClusterGenerator
          name: gluetun-token
