apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
components:
  - ../../common/system
resources:
  - externalsecret.yaml
  - gluetungateway.yaml
  - helmrelease.yaml
  - network.yaml
  - networkpolicy.yaml
  - rbac.yaml
