---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ${APP}-gateway
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "${APP}",
      "type": "bridge",
      "bridge": "gtn110${VPN_GATEWAY_ID}br",
      "ipMasq": false,
      "ipam": {
        "type": "static",
        "addresses": [
          { "address": "100.100.${VPN_GATEWAY_ID}.1/24" }
        ]
      },
      "mtu": 1420
    }
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ${APP}-client
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "${APP}-client",
      "type": "bridge",
      "bridge": "gtn110${VPN_GATEWAY_ID}br",
      "ipMasq": false,
      "ipam": {
        "type": "whereabouts",
        "range": "100.100.${VPN_GATEWAY_ID}.0/24",
        "range_start": "100.100.${VPN_GATEWAY_ID}.10",
        "range_end": "100.100.${VPN_GATEWAY_ID}.99",
        "gateway": "100.100.${VPN_GATEWAY_ID}.1",
        "routes": [
          { "dst": "0.0.0.0/5" },
          { "dst": "8.0.0.0/7" },
          { "dst": "11.0.0.0/8" },
          { "dst": "12.0.0.0/6" },
          { "dst": "16.0.0.0/4" },
          { "dst": "32.0.0.0/3" },
          { "dst": "64.0.0.0/2" },
          { "dst": "128.0.0.0/3" },
          { "dst": "160.0.0.0/5" },
          { "dst": "168.0.0.0/8" },
          { "dst": "169.0.0.0/9" },
          { "dst": "169.128.0.0/10" },
          { "dst": "169.192.0.0/11" },
          { "dst": "169.224.0.0/12" },
          { "dst": "169.240.0.0/13" },
          { "dst": "169.248.0.0/14" },
          { "dst": "169.252.0.0/15" },
          { "dst": "169.255.0.0/16" },
          { "dst": "170.0.0.0/7" },
          { "dst": "172.0.0.0/12" },
          { "dst": "172.32.0.0/11" },
          { "dst": "172.64.0.0/10" },
          { "dst": "172.128.0.0/9" },
          { "dst": "173.0.0.0/8" },
          { "dst": "174.0.0.0/7" },
          { "dst": "176.0.0.0/4" },
          { "dst": "192.0.0.0/9" },
          { "dst": "192.128.0.0/11" },
          { "dst": "192.160.0.0/13" },
          { "dst": "192.169.0.0/16" },
          { "dst": "192.170.0.0/15" },
          { "dst": "192.172.0.0/14" },
          { "dst": "192.176.0.0/12" },
          { "dst": "192.192.0.0/10" },
          { "dst": "193.0.0.0/8" },
          { "dst": "194.0.0.0/7" },
          { "dst": "196.0.0.0/6" },
          { "dst": "200.0.0.0/5" },
          { "dst": "208.0.0.0/4" },
          { "dst": "224.0.0.0/3" }
        ]
      },
      "mtu": 1420
    }
